In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import glob
import os
import pandas as pd

In [2]:
df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/star_cadences_h5_dat_receiver_wX.csv')
df

,Target,Distance,Cadence ID,Frequency,.h5 path,.dat path,Receiver (X split),Receiver
0,GJ1002,4.69,3635,1926,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr1_2,Rcvr1_2
1,GJ1002,4.69,3635,1926,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr1_2,Rcvr1_2
2,GJ1002,4.69,3635,1926,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr1_2,Rcvr1_2
3,GJ1002,4.69,3635,1926,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr1_2,Rcvr1_2
4,GJ1002,4.69,3635,1926,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr1_2,Rcvr1_2
...,...,...,...,...,...,...,...,...
282853,SO0253,3.85,421558,7876,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr8_10_NEW,Rcvr8_10
282854,SO0253,3.85,421558,7876,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr8_10_NEW,Rcvr8_10
282855,SO0253,3.85,421558,7876,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr8_10_NEW,Rcvr8_10
282856,SO0253,3.85,421558,7876,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr8_10_NEW,Rcvr8_10
282857,SO0253,3.85,421558,7876,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,Rcvr8_10_NEW,Rcvr8_10

In [3]:
full_target_list = df['Target'].values
full_cadence_id_list = df['Cadence ID'].values
full_h5_list = df['.h5 path'].values
full_dat_list = df['.dat path'].values
full_receiver_list = df['Receiver (X split)'].values

In [4]:
df0 = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/BL_star_targets_all_sky.csv')
dfu = df0.drop(983) # remove duplicate entry for HIP 97222
dfu

,Name,RA,DEC,Vmag,Sp.Type,dist (pc),ObsDate,Unnamed: 7
0,HIP2,0 0 1.22,-19 29 55,9.27,K3V,45.6,12/13/2020,NaN
1,HIP171,0 2 11.0,27 4 41,5.80,G3V,12.4,11/13/2020,NaN
2,HIP194,0 2 29.6,8 29 6,5.70,F0V,37.6,08/21/2020,NaN
3,HIP400,0 4 56.7,23 16 10,7.82,G9V,25.6,01/19/2020,NaN
4,HIP428,0 5 12.2,45 47 9,9.95,M2,11.4,12/01/2019,NaN
...,...,...,...,...,...,...,...,...
1176,HIP117795,23 53 20.0,59 56 42,10.40,K8,27.3,07/04/2019,NaN
1177,HIP117946,23 55 26.8,22 11 33,8.77,K0,25.4,08/02/2019,NaN
1178,HIP118162,23 58 6.74,50 26 55,6.72,G5,24.1,07/04/2019,NaN
1179,HIP118212,23 58 44.5,46 43 44,9.57,M0,17.3,07/04/2019,NaN
1180,HIP118310,23 59 47.7,6 39 48,8.85,K5,25.3,10/23/2019,NaN

In [5]:
for i in np.sort(dfu['Name'].values.astype(str)):
    print(i)

GJ1002
GJ1111
GJ1245AC
GJ1245B
GJ144
GJ15A
GJ15B
GJ166
GJ166BC
GJ234
GJ244
GJ273
GJ280
GJ380
GJ388
GJ406
GJ411
GJ412A
GJ412B
GJ447
GJ473AB
GJ54.1
GJ628
GJ65A
GJ687
GJ699
GJ702A
GJ702B
GJ71
GJ725
GJ768
GJ820A
GJ820B
GJ83.1
GJ860A
GJ860B
GJ866
GJ873
GJ876
GJ905
HIP100017
HIP100064
HIP100511
HIP100859
HIP101027
HIP101093
HIP101150
HIP101180
HIP101262
HIP101382
HIP101955
HIP102040
HIP102101
HIP102226
HIP102253
HIP102422
HIP102488
HIP102531
HIP102532
HIP102766
HIP10279
HIP102805
HIP102843
HIP102851
HIP102870
HIP103039
HIP10306
HIP103096
HIP103256
HIP103388
HIP103441
HIP103650
HIP103800
HIP103859
HIP104019
HIP104092
HIP104139
HIP10416
HIP104239
HIP104383
HIP104521
HIP104887
HIP105038
HIP105152
HIP105199
HIP105341
HIP105406
HIP10542
HIP105668
HIP105769
HIP105860
HIP105932
HIP106106
HIP106147
HIP106231
HIP106400
HIP10644
HIP106481
HIP10670
HIP106811
HIP106897
HIP10723
HIP107346
HIP107350
HIP107556
HIP107788
HIP107975
HIP108028
HIP108036
HIP108092
HIP108156
HIP108506
HIP1086
HIP108752
HIP108782
HIP108917
HIP109176
HIP109378
HIP109388
HIP109427
HIP109474
HIP109527
HIP109555
HIP109638
HIP109822
HIP109857
HIP109926
HIP109980
HIP11000
HIP11029
HIP110341
HIP110395
HIP11048
HIP110526
HIP110640
HIP110750
HIP110774
HIP110778
HIP11090
HIP110951
HIP111169
HIP111170
HIP111313
HIP111685
HIP111888
HIP112190
HIP112245
HIP112496
HIP112527
HIP112724
HIP112748
HIP112774
HIP112870
HIP112909
HIP112915
HIP112918
HIP112935
HIP113357
HIP113409
HIP113421
HIP113718
HIP113829
HIP113944
HIP113963
HIP114189
HIP114233
HIP114379
HIP114430
HIP114456
HIP11452
HIP114570
HIP114622
HIP114886
HIP114924
HIP114971
HIP115142
HIP115147
HIP115331
HIP115341
HIP115445
HIP115562
HIP11565
HIP11569
HIP115738
HIP116085
HIP116106
HIP116215
HIP116384
HIP116416
HIP116495
HIP116584
HIP116613
HIP116727
HIP116758
HIP116771
HIP116819
HIP116838
HIP116936
HIP116971
HIP117197
HIP117410
HIP117463
HIP117473
HIP117559
HIP11759
HIP117712
HIP117779
HIP117795
HIP11783
HIP117946
HIP118162
HIP118212
HIP118310
HIP120005
HIP12097
HIP12114
HIP12158
HIP12390
HIP1242
HIP12444
HIP12447
HIP12493
HIP12530
HIP12706
HIP12709
HIP12777
HIP12781
HIP12828
HIP12832
HIP12843
HIP12929
HIP13081
HIP13258
HIP13375
HIP13402
HIP13601
HIP13642
HIP13665
HIP1368
HIP13834
HIP13976
HIP14150
HIP14286
HIP14293
HIP1444
HIP14445
HIP14576
HIP1463
HIP14632
HIP14633
HIP14668
HIP14669
HIP14729
HIP1473
HIP14862
HIP14954
HIP1499
HIP15099
HIP15197
HIP15220
HIP1532
HIP15411
HIP15457
HIP15638
HIP15648
HIP15673
HIP15797
HIP15919
HIP16134
HIP16499
HIP16846
HIP16852
HIP1692
HIP17027
HIP171
HIP17147
HIP17378
HIP17395
HIP17405
HIP17414
HIP17420
HIP17496
HIP17609
HIP17666
HIP17749
HIP1803
HIP18267
HIP18280
HIP18324
HIP18413
HIP18512
HIP18774
HIP18859
HIP18907
HIP18975
HIP19076
HIP19205
HIP19255
HIP19335
HIP19337
HIP194
HIP19422
HIP19554
HIP19655
HIP19719
HIP19832
HIP19849
HIP19855
HIP19859
HIP19930
HIP19990
HIP2
HIP20219
HIP20261
HIP20542
HIP20635
HIP20641
HIP20648
HIP20713
HIP20842
HIP20901
HIP20917
HIP21029
HIP21036
HIP21039
HIP2120
HIP21272
HIP21273
HIP21402
HIP21421
HIP21482
HIP21547
HIP21553
HIP21556
HIP21589
HIP21594
HIP21673
HIP21683
HIP21818
HIP21932
HIP21988
HIP22044
HIP22263
HIP22287
HIP22288
HIP22361
HIP22449
HIP22498
HIP22627
HIP22715
HIP22762
HIP22845
HIP23147
HIP23179
HIP23296
HIP23311
HIP23497
HIP23512
HIP23783
HIP23786
HIP23875
HIP23932
HIP23941
HIP2422
HIP24284
HIP24332
HIP24340
HIP24454
HIP24786
HIP24813
HIP24819
HIP24874
HIP25110
HIP25119
HIP25220
HIP25278
HIP25486
HIP2552
HIP25578
HIP25623
HIP25878
HIP26335
HIP26366
HIP26505
HIP26563
HIP26624
HIP26779
HIP26801
HIP26857
HIP27188
HIP27207
HIP27288
HIP27435
HIP2762
HIP27803
HIP27913
HIP27918
HIP27922
HIP28103
HIP28267
HIP28368
HIP28614
HIP28954
HIP29067
HIP29277
HIP29432
HIP29525
HIP29548
HIP29650
HIP29761
HIP29800
HIP29860
HIP30060
HIP30112
HIP30419
HIP30630
HIP30756
HIP3092
HIP3093
HIP31167
HIP31592
HIP31635
HIP31703
HIP32010
HIP3206
HIP32423
HIP32439
HIP32480
HIP32617
HIP32769
HIP32851
HIP32919
HIP32984
HIP33142
HIP33202
HIP33226
HIP33277
HIP33373
HIP33428
HIP33537
HIP33560
HIP33852
HIP33955
HIP34017
HIP34104
HIP34115
HIP3418
HIP3419
HIP34341
HIP34414
HIP34567
HIP34950
HIP35136
HIP35191
HIP3535
HIP35350
HIP35550
HIP35643
HIP35821
HIP35872
HIP36046
HIP36121
HIP36152
HIP36357
HIP36366
HIP36393
HIP36399
HIP36439
HIP36551
HIP36627
HIP36704
HIP36827
HIP36850
HIP36915
HIP36985
HIP37288
HIP37349
HIP37494
HIP37629
HIP3765
HIP37766
HIP37826
HIP38048
HIP38082
HIP38117
HIP3821
HIP38228
HIP38325
HIP38382
HIP38625
HIP38657
HIP38712
HIP3876
HIP38784
HIP38931
HIP38956
HIP39064
HIP3909
HIP39157
HIP39494
HIP3979
HIP39826
HIP39896
HIP3998
HIP400
HIP40035
HIP40118
HIP40239
HIP40375
HIP40501
HIP40671
HIP40693
HIP40774
HIP40843
HIP40875
HIP40910
HIP41130
HIP41211
HIP41307
HIP41484
HIP4151
HIP41689
HIP42074
HIP42080
HIP42172
HIP42173
HIP42220
HIP42333
HIP42418
HIP42438
HIP42499
HIP42748
HIP42762
HIP428
HIP42806
HIP4288
HIP42940
HIP43233
HIP43534
HIP43557
HIP43587
HIP43667
HIP43726
HIP43790
HIP43852
HIP43970
HIP44001
HIP44072
HIP44075
HIP44127
HIP44248
HIP44295
HIP443
HIP4436
HIP4454
HIP44722
HIP44897
HIP44901
HIP44955
HIP44984
HIP45038
HIP45075
HIP45170
HIP45336
HIP45343
HIP45383
HIP45493
HIP45617
HIP45688
HIP45836
HIP45839
HIP45963
HIP46199
HIP46343
HIP46417
HIP46509
HIP46549
HIP46580
HIP46706
HIP46733
HIP46769
HIP46816
HIP46843
HIP46853
HIP47080
HIP47201
HIP47300
HIP47513
HIP47690
HIP47701
HIP47741
HIP48336
HIP48390
HIP48411
HIP4845
HIP48477
HIP4849
HIP4856
HIP48714
HIP4872
HIP48833
HIP4907
HIP49081
HIP49127
HIP49197
HIP49366
HIP49544
HIP49593
HIP49669
HIP49699
HIP49809
HIP49841
HIP49868
HIP49969
HIP49973
HIP49986
HIP50125
HIP50341
HIP50372
HIP50384
HIP50485
HIP50505
HIP50564
HIP50583
HIP50782
HIP50944
HIP51007
HIP5110
HIP51248
HIP51254
HIP51317
HIP51384
HIP51459
HIP51468
HIP51502
HIP51525
HIP51547
HIP51658
HIP518
HIP51814
HIP51819
HIP51933
HIP52316
HIP52369
HIP52422
HIP52469
HIP5247
HIP52470
HIP52600
HIP5286
HIP53020
HIP5310
HIP53229
HIP5336
HIP5346
HIP53486
HIP53580
HIP5364
HIP5369
HIP53721
HIP53767
HIP53824
HIP53910
HIP53954
HIP53985
HIP54061
HIP54155
HIP54182
HIP544
HIP54426
HIP54459
HIP54646
HIP54651
HIP54677
HIP54745
HIP54810
HIP54872
HIP54906
HIP54952
HIP54966
HIP5521
HIP55210
HIP55360
HIP5542
HIP55705
HIP55718
HIP55846
HIP55848
HIP56035
HIP56157
HIP56199
HIP56238
HIP56242
HIP56445
HIP56630
HIP56802
HIP56809
HIP56829
HIP56997
HIP57274
HIP57328
HIP57493
HIP57494
HIP57632
HIP57757
HIP57802
HIP57866
HIP5799
HIP58001
HIP58576
HIP58684
HIP59000
HIP59280
HIP59378
HIP5938
HIP59406
HIP5944
HIP59496
HIP59504
HIP59514
HIP5957
HIP59608
HIP59750
HIP59774
HIP59816
HIP60303
HIP60559
HIP6069
HIP60759
HIP60866
HIP60910
HIP60965
HIP60994
HIP61053
HIP61094
HIP61099
HIP61100
HIP61174
HIP61212
HIP61317
HIP61329
HIP61481
HIP61901
HIP61941
HIP61946
HIP62145
HIP62207
HIP62505
HIP62512
HIP62523
HIP62687
HIP6290
HIP62956
HIP63076
HIP63121
HIP63257
HIP63366
HIP63406
HIP6344
HIP63467
HIP63503
HIP63510
HIP63608
HIP63742
HIP63762
HIP6379
HIP63894
HIP63942
HIP64048
HIP64241
HIP64394
HIP64457
HIP64577
HIP64725
HIP64792
HIP64797
HIP64924
HIP65011
HIP65026
HIP65143
HIP65327
HIP65343
HIP65352
HIP65355
HIP6537
HIP65378
HIP65420
HIP65477
HIP65515
HIP65530
HIP65714
HIP65859
HIP66077
HIP66147
HIP66193
HIP66222
HIP66249
HIP66252
HIP66459
HIP66492
HIP66675
HIP66704
HIP66781
HIP66840
HIP66886
HIP6706
HIP67090
HIP67105
HIP67155
HIP67164
HIP67275
HIP67301
HIP67422
HIP6748
HIP67691
HIP677
HIP67808
HIP68030
HIP6813
HIP68184
HIP68337
HIP68469
HIP68634
HIP68682
HIP6917
HIP69357
HIP69414
HIP69483
HIP69526
HIP69562
HIP69673
HIP69713
HIP69732
HIP69824
HIP69962
HIP69989
HIP70016
HIP70218
HIP70319
HIP70400
HIP70475
HIP70497
HIP70529
HIP70536
HIP7078
HIP70857
HIP70865
HIP70950
HIP70952
HIP70956
HIP71075
HIP71181
HIP71253
HIP71284
HIP71311
HIP71395
HIP71743
HIP71914
HIP71957
HIP72044
HIP72146
HIP72220
HIP72237
HIP72312
HIP72567
HIP72603
HIP72607
HIP72622
HIP72659
HIP72848
HIP72875
HIP72944
HIP73005
HIP73100
HIP73165
HIP7339
HIP73457
HIP73470
HIP73695
HIP73996
HIP74190
HIP74537
HIP74666
HIP74689
HIP74702
HIP74926
HIP74981
HIP74995
HIP75101
HIP7513
HIP75201
HIP75253
HIP75266
HIP75277
HIP75312
HIP7535
HIP75458
HIP75718
HIP75722
HIP7576
HIP75761
HIP75809
HIP75829
HIP76219
HIP76233
HIP76267
HIP76315
HIP76375
HIP76568
HIP76602
HIP76603
HIP76779
HIP76832
HIP76952
HIP77052
HIP77060
HIP77070
HIP77233
HIP77257
HIP7734
HIP77349
HIP77408
HIP77409
HIP77464
HIP7748
HIP77516
HIP77622
HIP77655
HIP77660
HIP77725
HIP77760
HIP77801
HIP78072
HIP78180
HIP78241
HIP78286
HIP78353
HIP78459
HIP78709
HIP78775
HIP78913
HIP79119
HIP79137
HIP7918
HIP79248
HIP79492
HIP79607
HIP79672
HIP79702
HIP79755
HIP79762
HIP79796
HIP7981
HIP79822
HIP79882
HIP80008
HIP80093
HIP80179
HIP80331
HIP80366
HIP80459
HIP80480
HIP8051
HIP80628
HIP80644
HIP8070
HIP80725
HIP81300
HIP81348
HIP81375
HIP81813
HIP81833
HIP81919
HIP82003
HIP82020
HIP82333
HIP82389
HIP82587
HIP82588
HIP8275
HIP82817
HIP82860
HIP83000
HIP83006
HIP83020
HIP83043
HIP83207
HIP83389
HIP83451
HIP83591
HIP83599
HIP83601
HIP83608
HIP83613
HIP8362
HIP83762
HIP83945
HIP83988
HIP83996
HIP84012
HIP84123
HIP84183
HIP84195
HIP84223
HIP84379
HIP84521
HIP84607
HIP84616
HIP84790
HIP8486
HIP84862
HIP8497
HIP85042
HIP85157
HIP85235
HIP85295
HIP85365
HIP8543
HIP85582
HIP85653
HIP85665
HIP85699
HIP85810
HIP85819
HIP85829
HIP85922
HIP86032
HIP86036
HIP86087
HIP86141
HIP86201
HIP86282
HIP86287
HIP86340
HIP86400
HIP86456
HIP86614
HIP86620
HIP86623
HIP86722
HIP86742
HIP86776
HIP87108
HIP87558
HIP87579
HIP87585
HIP87768
HIP87938
HIP88175
HIP88348
HIP88574
HIP88601
HIP88622
HIP8867
HIP88684
HIP88745
HIP88771
HIP88972
HIP8903
HIP89087
HIP89348
HIP89474
HIP89560
HIP89825
HIP89937
HIP89962
HIP90035
HIP90139
HIP90376
HIP90626
HIP90656
HIP90790
HIP9094
HIP90959
HIP90979
HIP910
HIP91009
HIP91128
HIP91217
HIP91237
HIP91262
HIP91430
HIP9153
HIP916
HIP91605
HIP91608
HIP91699
HIP91919
HIP91926
HIP91971
HIP91973
HIP92043
HIP92161
HIP92200
HIP92270
HIP92283
HIP92311
HIP92549
HIP92573
HIP9269
HIP92871
HIP92919
HIP92946
HIP92951
HIP92984
HIP93017
HIP93101
HIP93185
HIP93408
HIP93747
HIP93805
HIP93843
HIP93871
HIP93873
HIP93899
HIP93917
HIP94083
HIP94346
HIP94349
HIP94376
HIP94650
HIP94779
HIP9480
HIP9487
HIP95319
HIP95501
HIP95575
HIP95730
HIP95853
HIP9598
HIP95995
HIP96085
HIP96100
HIP96183
HIP96229
HIP96258
HIP96285
HIP96395
HIP96441
HIP96895
HIP96901
HIP97051
HIP9716
HIP97222
HIP97223
HIP9724
HIP9727
HIP97295
HIP974
HIP97649
HIP97650
HIP97675
HIP98036
HIP98192
HIP98204
HIP9829
HIP98416
HIP98505
HIP98677
HIP98698
HIP98767
HIP98792
HIP98819
HIP98828
HIP9884
HIP98906
HIP98921
HIP99031
HIP99316
HIP99427
HIP99452
HIP99572
HIP99655
HIP99711
HIP99742
HIP99764
HIP99770
HIP99880
LHS292
SO0253

In [6]:
u = np.unique(dfu['Sp.Type'].values.astype(str))
print(u)
print(len(u))
print(len(dfu['Sp.Type'].values.astype(str)))

['A0V' 'A0V SB' 'A0Vn' 'A0Vvar' 'A0p' 'A0sh' 'A1IV' 'A1V' 'A1Vnn' 'A1Vs'
 'A1m' 'A2' 'A2.5Va' 'A2IV' 'A2Ia+..' 'A2V' 'A2Vann' 'A2Vm' 'A2Vnn' 'A2Vs'
 'A2m' 'A3IIIva' 'A3IV' 'A3IV-Vn' 'A3IVv S' 'A3V' 'A3V...' 'A3Vn' 'A3Vvar'
 'A3m' 'A4IV' 'A4IVs' 'A4V' 'A4Vn' 'A4m' 'A4me...' 'A5III' 'A5IV' 'A5V'
 'A5V SB' 'A5V...' 'A5Vn' 'A5m' 'A5mF2 (' 'A5n' 'A5p Sr' 'A6IV' 'A6V'
 'A7III' 'A7III-I' 'A7IIIva' 'A7IV' 'A7IV-V' 'A7V' 'A7Vvar' 'A7m' 'A7s'
 'A8IV' 'A8V' 'A8Vn' 'A8Vs' 'A8m' 'A9IV' 'A9V' 'Am' 'Am...' 'B3V SB' 'B7V'
 'B8V' 'B9.5III' 'B9.5V' 'B9V' 'B9Vn' 'B9p' 'F0III' 'F0III-I' 'F0IV'
 'F0IV...' 'F0IVvar' 'F0V' 'F0V+...' 'F0V...' 'F0V:' 'F0Vn' 'F0Vnn+.'
 'F0Vp' 'F0p' 'F1III-I' 'F1IV' 'F1V' 'F2' 'F2/F3IV' 'F2III' 'F2III-I'
 'F2IV' 'F2V' 'F2V:var' 'F2p' 'F3III' 'F3IV' 'F3IV-V' 'F3IV/V' 'F3V'
 'F3V...' 'F3V:' 'F3Vwvar' 'F4IIIva' 'F4IV' 'F4IV-V' 'F4V' 'F4Vw' 'F5'
 'F5+...' 'F5/F6V' 'F5III' 'F5IV' 'F5IV-V' 'F5V' 'F5Vawva' 'F6IV' 'F6IV-V'
 'F6IVwva' 'F6V' 'F6Vbwva' 'F6Vs' 'F6Vvar' 'F7.7V' 'F7/F8IV' 'F7IV'
 'F7IV-V' 'F7V' 'F7V com' 'F7V:' 'F7Vvar' 'F8' 'F8V' 'F8V SB' 'F8V...'
 'F8Vw' 'F9V' 'G' 'G0' 'G0.5IV' 'G0.5Vb' 'G0IV' 'G0IV...' 'G0V' 'G0V SB'
 'G0Vs' 'G0Vvar' 'G1.5Vb' 'G1/G2V' 'G1V' 'G2/G3V' 'G2V' 'G2V + G' 'G3V'
 'G4V' 'G5' 'G5IV' 'G5IV/V' 'G5V' 'G5Vp' 'G5Vvar' 'G6/G8II' 'G6IV+..'
 'G6V' 'G7III' 'G7V' 'G8.5V' 'G8III' 'G8III-I' 'G8III/I' 'G8IIIva' 'G8IV'
 'G8IV-V' 'G8IV-V+' 'G8IVvar' 'G8V' 'G8V + K' 'G8Vvar' 'G9III' 'G9III+.'
 'G9IV-V' 'G9IVa' 'G9V' 'K' 'K0' 'K0...' 'K0.0V' 'K0.5V' 'K0/K1V' 'K0III'
 'K0III-I' 'K0IIIva' 'K0IV' 'K0IV-V' 'K0V' 'K0V SB' 'K0Ve' 'K1+...'
 'K1III' 'K1III S' 'K1III+.' 'K1IV' 'K1V' 'K2' 'K2.0V' 'K2III' 'K2IIIp'
 'K2IIIva' 'K2V' 'K2V:' 'K3/K4V' 'K3III' 'K3III..' 'K3V' 'K3Vvar' 'K4'
 'K4.5' 'K4/K5V' 'K4IIIva' 'K4V' 'K4V...' 'K5' 'K5.0V' 'K5/M0V' 'K5III'
 'K5IV' 'K5V' 'K5V...' 'K6' 'K6:' 'K6V:' 'K7' 'K7.0V' 'K7V' 'K7V:'
 'K7Vvar' 'K8' 'K8V' 'K8V:' 'K:' 'K:...' 'M' 'M0' 'M0...' 'M0.5V' 'M0.5V:'
 'M0.5V:e' 'M0:' 'M0V' 'M0V:' 'M0V:p' 'M0V:p..' 'M0Vvar' 'M0p' 'M1'
 'M1.0V' 'M1.5V' 'M1.5Ve' 'M1:' 'M1V' 'M1V...' 'M1V:' 'M1Vvar' 'M2'
 'M2.0V' 'M2.5V' 'M2.5Ve' 'M2:' 'M2III' 'M2V' 'M2V:' 'M2Ve' 'M3' 'M3.0V'
 'M3.5' 'M3.5V' 'M3.5Ve' 'M3.5e' 'M3V' 'M3V:' 'M3Ve' 'M4' 'M4+...' 'M4.0V'
 'M4.5V' 'M4.5Ve' 'M4:' 'M4V' 'M4Ve' 'M5' 'M5.0V' 'M5.5V' 'M5V' 'M6.0V'
 'M6.5V' 'M6V' 'M9' 'M:' 'nan']
302
1180

In [ ]:
cadences_info = []

for i in range(len(full_h5_list)//6):

    print(f'#{i+1} of {len(full_h5_list)//6} files ...')

    # for each set of 6 files, run FindEvent and PlotEvent

    h5_list = full_h5_list[6*i:6*i+6]
    dat_list = full_dat_list[6*i:6*i+6]

    # check that all h5 files in cadence exist and were searched
    # (not true for 3 files, 5 occurrences)
    #if 'None' in dat_list:
    #    continue

    target = full_target_list[6*i]
    cadence_id = full_cadence_id_list[6*i]
    receiver = full_receiver_list[6*i]
    s = dat_list[0].split('blc')
    if ('spliced' in dat_list[0]) & (s[1][2] == '_'):
        node = 'blc'+s[1][:2]
    else:
        node = os.path.basename(full_h5_list[6*i])[:5]

    # This block checks the cadence type:
    # Either ABACAD, BACADA, or None (if not a real cadence).
    # ABABAB is also checked, but does not occur in this dataset.
    #cadences = full_cadence_id_list[6*i:6*i+6]
    #receivers = np.unique(full_receiver_list[6*i:6*i+6])
    targets = []
    for j in range(6):
        t = df['.h5 path'].values[6*i+j].split('guppi_')[1][12:-21]
        if len(t) < 3:
            t = df['.h5 path'].values[6*i+j].split('guppi_')[1][6:-21] # account for GJ15B cadence listed with only integer MJD
        targets.append(t.upper()) # some stars not recorded in all uppercase
    odd_targets = np.unique(targets[::2])
    even_targets = np.unique(targets[1::2])
    cadence_type = 'None'
    off_check = 0
    for t in odd_targets:
        if 'OFF' in t:
            if len(even_targets) == 1:
                cadence_type = 'BACADA'
            off_check += 1
    for t in even_targets:
        if 'OFF' in t:
            if len(odd_targets) == 1:
                cadence_type = 'ABACAD'
            off_check += 1
    if (cadence_type == 'None') & (off_check == 0):
        n_odd_ons = len(np.unique(targets[::2]))
        n_even_ons = len(np.unique(targets[1::2]))
        if (n_odd_ons == 1) & (n_even_ons == 1):
            cadence_type = 'ABABAB'
        if (n_odd_ons == 1) & (n_even_ons != 1):
            cadence_type = 'ABACAD'
        if (n_odd_ons != 1) & (n_even_ons == 1):
            cadence_type = 'BACADA'

    #if not cadence_id == 4051:
    #    continue
    if cadence_type == 'ABACAD':
        target = targets[0]
    elif cadence_type == 'BACADA':
        target = targets[1]
    elif cadence_type == 'ABABAB':
        ### NEED TO SORT THIS OUT
        ### Add BOTH cadences and then figure out later which is real.
        ### This will mean rerunning the FindEvent code in the BABABA configuration for each of these cadences.
        ### Some will have both A and B in the BL star sample; some will have only one.

    #print(f'{cadence_id} {cadence_type} {target} {receiver} {targets}')

    #if cadence_type == 'None':
    #    continue

    #print(node)
    #print(dat_list[0])

    in_sample = 'Yes'

    additional_data = dfu.iloc[np.where(dfu['Name'].values == target)[0]]
    if len(additional_data) == 0:
        in_sample = 'No'
        print(f'{target} not found in dataframe!')
        cadences_info.append([
            target,
            np.nan,
            np.nan,
            np.nan,
            cadence_id,
            cadence_type,
            receiver,
            np.nan,
            np.nan,
            h5_list[0],
            h5_list[1],
            h5_list[2],
            h5_list[3],
            h5_list[4],
            h5_list[5],
            dat_list[0],
            dat_list[1],
            dat_list[2],
            dat_list[3],
            dat_list[4],
            dat_list[5]
        ])
        continue

    ra = additional_data['RA'].values[0]
    dec = additional_data['DEC'].values[0]
    vmag = additional_data['Vmag'].values[0]
    sptype = additional_data['Sp.Type'].values[0]
    dist = additional_data['dist (pc)'].values[0]

    cadences_info.append([
        target,
        ra,
        dec,
        dist,
        cadence_id,
        cadence_type,
        receiver,
        vmag,
        sptype,
        h5_list[0],
        h5_list[1],
        h5_list[2],
        h5_list[3],
        h5_list[4],
        h5_list[5],
        dat_list[0],
        dat_list[1],
        dat_list[2],
        dat_list[3],
        dat_list[4],
        dat_list[5]
    ])

cadence_keys = [
    'Target',
    'RA',
    'DEC',
    'Distance (pc)',
    'Cadence ID',
    'Cadence Type',
    'Receiver',
    'Vmag',
    'Spectral Type',
    '.h5 path 1',
    '.h5 path 2',
    '.h5 path 3',
    '.h5 path 4',
    '.h5 path 5',
    '.h5 path 6',
    '.dat path 1',
    '.dat path 2',
    '.dat path 3',
    '.dat path 4',
    '.dat path 5',
    '.dat path 6'
]

dfc = pd.DataFrame(data=cadences_info, columns=cadence_keys)
dfc
    # if (target == 'GJ412B') & (node == 'blc04') & (receiver == 'Rcvr1_2'):
    #     start_counter += 1
    
    # if start_counter == 0:
    #     continue

#1 of 47143 files ...
#2 of 47143 files ...
#3 of 47143 files ...
#4 of 47143 files ...
#5 of 47143 files ...
#6 of 47143 files ...
#7 of 47143 files ...
#8 of 47143 files ...
#9 of 47143 files ...
#10 of 47143 files ...
#11 of 47143 files ...
#12 of 47143 files ...
#13 of 47143 files ...
#14 of 47143 files ...
#15 of 47143 files ...
#16 of 47143 files ...
#17 of 47143 files ...
#18 of 47143 files ...
#19 of 47143 files ...
#20 of 47143 files ...
#21 of 47143 files ...
#22 of 47143 files ...
#23 of 47143 files ...
#24 of 47143 files ...
#25 of 47143 files ...
#26 of 47143 files ...
#27 of 47143 files ...
#28 of 47143 files ...
#29 of 47143 files ...
#30 of 47143 files ...
#31 of 47143 files ...
#32 of 47143 files ...
#33 of 47143 files ...
#34 of 47143 files ...
#35 of 47143 files ...
#36 of 47143 files ...
#37 of 47143 files ...
#38 of 47143 files ...
#39 of 47143 files ...
#40 of 47143 files ...
#41 of 47143 files ...
#42 of 47143 files ...
#43 of 47143 files ...
#44 of 47143 files ...
#45 of 47143 files ...
#46 of 47143 files ...
#47 of 47143 files ...
#48 of 47143 files ...
#49 of 47143 files ...
#50 of 47143 files ...
#51 of 47143 files ...
#52 of 47143 files ...
#53 of 47143 files ...
#54 of 47143 files ...
#55 of 47143 files ...
#56 of 47143 files ...
#57 of 47143 files ...
#58 of 47143 files ...
#59 of 47143 files ...
#60 of 47143 files ...
#61 of 47143 files ...
#62 of 47143 files ...
#63 of 47143 files ...
#64 of 47143 files ...
#65 of 47143 files ...
#66 of 47143 files ...
#67 of 47143 files ...
#68 of 47143 files ...
#69 of 47143 files ...
#70 of 47143 files ...
#71 of 47143 files ...
#72 of 47143 files ...
#73 of 47143 files ...
#74 of 47143 files ...
#75 of 47143 files ...
#76 of 47143 files ...
#77 of 47143 files ...
#78 of 47143 files ...
#79 of 47143 files ...
#80 of 47143 files ...
#81 of 47143 files ...
#82 of 47143 files ...
#83 of 47143 files ...
#84 of 47143 files ...
#85 of 47143 files ...
#86 of 47143 files ...
#87 of 47143 files ...
#88 of 47143 files ...
#89 of 47143 files ...
#90 of 47143 files ...
#91 of 47143 files ...
#92 of 47143 files ...
#93 of 47143 files ...
#94 of 47143 files ...
#95 of 47143 files ...
#96 of 47143 files ...
#97 of 47143 files ...
#98 of 47143 files ...
#99 of 47143 files ...
#100 of 47143 files ...
#101 of 47143 files ...
#102 of 47143 files ...
#103 of 47143 files ...
#104 of 47143 files ...
#105 of 47143 files ...
#106 of 47143 files ...
#107 of 47143 files ...
#108 of 47143 files ...
#109 of 47143 files ...
#110 of 47143 files ...
#111 of 47143 files ...
#112 of 47143 files ...
#113 of 47143 files ...
#114 of 47143 files ...
#115 of 47143 files ...
#116 of 47143 files ...
#117 of 47143 files ...
#118 of 47143 files ...
#119 of 47143 files ...
#120 of 47143 files ...
#121 of 47143 files ...
#122 of 47143 files ...
#123 of 47143 files ...
#124 of 47143 files ...
#125 of 47143 files ...
#126 of 47143 files ...
#127 of 47143 files ...
#128 of 47143 files ...
#129 of 47143 files ...
#130 of 47143 files ...
#131 of 47143 files ...
#132 of 47143 files ...
#133 of 47143 files ...
#134 of 47143 files ...
#135 of 47143 files ...
#136 of 47143 files ...
#137 of 47143 files ...
#138 of 47143 files ...
#139 of 47143 files ...
#140 of 47143 files ...
#141 of 47143 files ...
#142 of 47143 files ...
#143 of 47143 files ...
#144 of 47143 files ...
#145 of 47143 files ...
#146 of 47143 files ...
#147 of 47143 files ...
#148 of 47143 files ...
#149 of 47143 files ...
#150 of 47143 files ...
#151 of 47143 files ...
#152 of 47143 files ...
#153 of 47143 files ...
#154 of 47143 files ...
#155 of 47143 files ...
#156 of 47143 files ...
#157 of 47143 files ...
#158 of 47143 files ...
#159 of 47143 files ...
#160 of 47143 files ...
#161 of 47143 files ...
#162 of 47143 files ...
#163 of 47143 files ...
#164 of 47143 files ...
#165 of 47143 files ...
#166 of 47143 files ...
#167 of 47143 files ...
#168 of 47143 files ...
#169 of 47143 files ...
#170 of 47143 files ...
#171 of 47143 files ...
#172 of 47143 files ...
#173 of 47143 files ...
#174 of 47143 files ...
#175 of 47143 files ...
#176 of 47143 files ...
#177 of 47143 files ...
#178 of 47143 files ...
#179 of 47143 files ...
#180 of 47143 files ...
#181 of 47143 files ...
#182 of 47143 files ...
#183 of 47143 files ...
#184 of 47143 files ...
#185 of 47143 files ...
#186 of 47143 files ...
#187 of 47143 files ...
#188 of 47143 files ...
#189 of 47143 files ...
#190 of 47143 files ...
#191 of 47143 files ...
#192 of 47143 files ...
#193 of 47143 files ...
#194 of 47143 files ...
#195 of 47143 files ...
#196 of 47143 files ...
#197 of 47143 files ...
#198 of 47143 files ...
#199 of 47143 files ...
#200 of 47143 files ...
#201 of 47143 files ...
#202 of 47143 files ...
#203 of 47143 files ...
#204 of 47143 files ...
#205 of 47143 files ...
#206 of 47143 files ...
#207 of 47143 files ...
#208 of 47143 files ...
#209 of 47143 files ...
#210 of 47143 files ...
#211 of 47143 files ...
#212 of 47143 files ...
#213 of 47143 files ...
#214 of 47143 files ...
#215 of 47143 files ...
#216 of 47143 files ...
#217 of 47143 files ...
#218 of 47143 files ...
#219 of 47143 files ...
#220 of 47143 files ...
#221 of 47143 files ...
#222 of 47143 files ...
#223 of 47143 files ...
#224 of 47143 files ...
#225 of 47143 files ...
#226 of 47143 files ...
#227 of 47143 files ...
#228 of 47143 files ...
#229 of 47143 files ...
#230 of 47143 files ...
#231 of 47143 files ...
#232 of 47143 files ...
#233 of 47143 files ...
#234 of 47143 files ...
#235 of 47143 files ...
#236 of 47143 files ...
#237 of 47143 files ...
#238 of 47143 files ...
#239 of 47143 files ...
#240 of 47143 files ...
#241 of 47143 files ...
#242 of 47143 files ...
#243 of 47143 files ...
#244 of 47143 files ...
#245 of 47143 files ...
#246 of 47143 files ...
#247 of 47143 files ...
#248 of 47143 files ...
#249 of 47143 files ...
#250 of 47143 files ...
#251 of 47143 files ...
#252 of 47143 files ...
#253 of 47143 files ...
#254 of 47143 files ...
#255 of 47143 files ...
#256 of 47143 files ...
#257 of 47143 files ...
#258 of 47143 files ...
#259 of 47143 files ...
#260 of 47143 files ...
#261 of 47143 files ...
#262 of 47143 files ...
#263 of 47143 files ...
#264 of 47143 files ...
#265 of 47143 files ...
#266 of 47143 files ...
#267 of 47143 files ...
#268 of 47143 files ...
#269 of 47143 files ...
#270 of 47143 files ...
#271 of 47143 files ...
#272 of 47143 files ...
#273 of 47143 files ...
#274 of 47143 files ...
#275 of 47143 files ...
#276 of 47143 files ...
#277 of 47143 files ...
#278 of 47143 files ...
#279 of 47143 files ...
#280 of 47143 files ...
#281 of 47143 files ...
#282 of 47143 files ...
#283 of 47143 files ...
#284 of 47143 files ...
#285 of 47143 files ...
#286 of 47143 files ...
#287 of 47143 files ...
#288 of 47143 files ...
#289 of 47143 files ...
#290 of 47143 files ...
#291 of 47143 files ...
#292 of 47143 files ...
#293 of 47143 files ...
#294 of 47143 files ...
#295 of 47143 files ...
#296 of 47143 files ...
#297 of 47143 files ...
#298 of 47143 files ...
#299 of 47143 files ...
#300 of 47143 files ...
#301 of 47143 files ...
#302 of 47143 files ...
#303 of 47143 files ...
#304 of 47143 files ...
#305 of 47143 files ...
#306 of 47143 files ...
#307 of 47143 files ...
#308 of 47143 files ...
#309 of 47143 files ...
#310 of 47143 files ...
#311 of 47143 files ...
#312 of 47143 files ...
#313 of 47143 files ...
#314 of 47143 files ...
#315 of 47143 files ...
#316 of 47143 files ...
#317 of 47143 files ...
#318 of 47143 files ...
#319 of 47143 files ...
#320 of 47143 files ...
#321 of 47143 files ...
#322 of 47143 files ...
#323 of 47143 files ...
#324 of 47143 files ...
#325 of 47143 files ...
#326 of 47143 files ...
#327 of 47143 files ...
#328 of 47143 files ...
#329 of 47143 files ...
#330 of 47143 files ...
#331 of 47143 files ...
#332 of 47143 files ...
#333 of 47143 files ...
#334 of 47143 files ...
#335 of 47143 files ...
#336 of 47143 files ...
#337 of 47143 files ...
#338 of 47143 files ...
#339 of 47143 files ...
#340 of 47143 files ...
#341 of 47143 files ...
#342 of 47143 files ...
#343 of 47143 files ...
#344 of 47143 files ...
#345 of 47143 files ...
#346 of 47143 files ...
#347 of 47143 files ...
#348 of 47143 files ...
#349 of 47143 files ...
#350 of 47143 files ...
#351 of 47143 files ...
#352 of 47143 files ...
#353 of 47143 files ...
#354 of 47143 files ...
#355 of 47143 files ...
#356 of 47143 files ...
#357 of 47143 files ...
#358 of 47143 files ...
#359 of 47143 files ...
#360 of 47143 files ...
#361 of 47143 files ...
#362 of 47143 files ...
#363 of 47143 files ...
#364 of 47143 files ...
#365 of 47143 files ...
#366 of 47143 files ...
#367 of 47143 files ...
#368 of 47143 files ...
#369 of 47143 files ...
#370 of 47143 files ...
#371 of 47143 files ...
#372 of 47143 files ...
#373 of 47143 files ...
#374 of 47143 files ...
#375 of 47143 files ...
#376 of 47143 files ...
#377 of 47143 files ...
#378 of 47143 files ...
#379 of 47143 files ...
#380 of 47143 files ...
#381 of 47143 files ...
#382 of 47143 files ...
#383 of 47143 files ...
#384 of 47143 files ...
#385 of 47143 files ...
#386 of 47143 files ...
#387 of 47143 files ...
#388 of 47143 files ...
#389 of 47143 files ...
#390 of 47143 files ...
#391 of 47143 files ...
#392 of 47143 files ...
#393 of 47143 files ...
#394 of 47143 files ...
#395 of 47143 files ...
#396 of 47143 files ...
#397 of 47143 files ...
#398 of 47143 files ...
#399 of 47143 files ...
#400 of 47143 files ...
#401 of 47143 files ...
#402 of 47143 files ...
#403 of 47143 files ...
#404 of 47143 files ...
#405 of 47143 files ...
#406 of 47143 files ...
#407 of 47143 files ...
#408 of 47143 files ...
#409 of 47143 files ...
#410 of 47143 files ...
#411 of 47143 files ...
#412 of 47143 files ...
#413 of 47143 files ...
#414 of 47143 files ...
#415 of 47143 files ...
#416 of 47143 files ...
#417 of 47143 files ...
#418 of 47143 files ...
#419 of 47143 files ...
#420 of 47143 files ...
#421 of 47143 files ...
#422 of 47143 files ...
#423 of 47143 files ...
#424 of 47143 files ...
#425 of 47143 files ...
#426 of 47143 files ...
#427 of 47143 files ...
#428 of 47143 files ...
#429 of 47143 files ...
#430 of 47143 files ...
#431 of 47143 files ...
#432 of 47143 files ...
#433 of 47143 files ...
#434 of 47143 files ...
#435 of 47143 files ...
#436 of 47143 files ...
#437 of 47143 files ...
#438 of 47143 files ...
#439 of 47143 files ...
#440 of 47143 files ...
#441 of 47143 files ...
#442 of 47143 files ...
#443 of 47143 files ...
#444 of 47143 files ...
#445 of 47143 files ...
#446 of 47143 files ...
#447 of 47143 files ...
#448 of 47143 files ...
#449 of 47143 files ...
#450 of 47143 files ...
#451 of 47143 files ...
#452 of 47143 files ...
#453 of 47143 files ...
#454 of 47143 files ...
#455 of 47143 files ...
#456 of 47143 files ...
#457 of 47143 files ...
#458 of 47143 files ...
#459 of 47143 files ...
#460 of 47143 files ...
#461 of 47143 files ...
#462 of 47143 files ...
#463 of 47143 files ...
#464 of 47143 files ...
#465 of 47143 files ...
#466 of 47143 files ...
#467 of 47143 files ...
#468 of 47143 files ...
#469 of 47143 files ...
#470 of 47143 files ...
#471 of 47143 files ...
#472 of 47143 files ...
#473 of 47143 files ...
#474 of 47143 files ...
#475 of 47143 files ...
#476 of 47143 files ...
#477 of 47143 files ...
#478 of 47143 files ...
#479 of 47143 files ...
#480 of 47143 files ...
#481 of 47143 files ...
#482 of 47143 files ...
#483 of 47143 files ...
#484 of 47143 files ...
#485 of 47143 files ...
#486 of 47143 files ...
#487 of 47143 files ...
#488 of 47143 files ...
#489 of 47143 files ...
#490 of 47143 files ...
#491 of 47143 files ...
#492 of 47143 files ...
#493 of 47143 files ...
#494 of 47143 files ...
#495 of 47143 files ...
HIP49183 not found in dataframe!
#496 of 47143 files ...
#497 of 47143 files ...
#498 of 47143 files ...
#499 of 47143 files ...
#500 of 47143 files ...
#501 of 47143 files ...
#502 of 47143 files ...
#503 of 47143 files ...
#504 of 47143 files ...
#505 of 47143 files ...
#506 of 47143 files ...
#507 of 47143 files ...
#508 of 47143 files ...
#509 of 47143 files ...
#510 of 47143 files ...
#511 of 47143 files ...
#512 of 47143 files ...
#513 of 47143 files ...
#514 of 47143 files ...
#515 of 47143 files ...
#516 of 47143 files ...
#517 of 47143 files ...
#518 of 47143 files ...
#519 of 47143 files ...
#520 of 47143 files ...
#521 of 47143 files ...
#522 of 47143 files ...
#523 of 47143 files ...
#524 of 47143 files ...
#525 of 47143 files ...
#526 of 47143 files ...
#527 of 47143 files ...
#528 of 47143 files ...
#529 of 47143 files ...
#530 of 47143 files ...
#531 of 47143 files ...
#532 of 47143 files ...
#533 of 47143 files ...
#534 of 47143 files ...
#535 of 47143 files ...
#536 of 47143 files ...
#537 of 47143 files ...
#538 of 47143 files ...
#539 of 47143 files ...
#540 of 47143 files ...
#541 of 47143 files ...
#542 of 47143 files ...
#543 of 47143 files ...
#544 of 47143 files ...
#545 of 47143 files ...
#546 of 47143 files ...
#547 of 47143 files ...
#548 of 47143 files ...
#549 of 47143 files ...
#550 of 47143 files ...
#551 of 47143 files ...
#552 of 47143 files ...
#553 of 47143 files ...
#554 of 47143 files ...
#555 of 47143 files ...
#556 of 47143 files ...
#557 of 47143 files ...
#558 of 47143 files ...
#559 of 47143 files ...
#560 of 47143 files ...
#561 of 47143 files ...
#562 of 47143 files ...
#563 of 47143 files ...
#564 of 47143 files ...
#565 of 47143 files ...
#566 of 47143 files ...
#567 of 47143 files ...
#568 of 47143 files ...
#569 of 47143 files ...
#570 of 47143 files ...
#571 of 47143 files ...
#572 of 47143 files ...
#573 of 47143 files ...
#574 of 47143 files ...
#575 of 47143 files ...
#576 of 47143 files ...
#577 of 47143 files ...
#578 of 47143 files ...
#579 of 47143 files ...
#580 of 47143 files ...
#581 of 47143 files ...
#582 of 47143 files ...
#583 of 47143 files ...
#584 of 47143 files ...
#585 of 47143 files ...
#586 of 47143 files ...
#587 of 47143 files ...
#588 of 47143 files ...
#589 of 47143 files ...
#590 of 47143 files ...
#591 of 47143 files ...
#592 of 47143 files ...
#593 of 47143 files ...
#594 of 47143 files ...
#595 of 47143 files ...
#596 of 47143 files ...
#597 of 47143 files ...
#598 of 47143 files ...
#599 of 47143 files ...
#600 of 47143 files ...
#601 of 47143 files ...
#602 of 47143 files ...
#603 of 47143 files ...
#604 of 47143 files ...
#605 of 47143 files ...
#606 of 47143 files ...
#607 of 47143 files ...
#608 of 47143 files ...
#609 of 47143 files ...
#610 of 47143 files ...
#611 of 47143 files ...
#612 of 47143 files ...
#613 of 47143 files ...
#614 of 47143 files ...
#615 of 47143 files ...
#616 of 47143 files ...
#617 of 47143 files ...
#618 of 47143 files ...
#619 of 47143 files ...
#620 of 47143 files ...
#621 of 47143 files ...
#622 of 47143 files ...
#623 of 47143 files ...
#624 of 47143 files ...
#625 of 47143 files ...
#626 of 47143 files ...
#627 of 47143 files ...
#628 of 47143 files ...
#629 of 47143 files ...
#630 of 47143 files ...
#631 of 47143 files ...
#632 of 47143 files ...
#633 of 47143 files ...
#634 of 47143 files ...
#635 of 47143 files ...
#636 of 47143 files ...
#637 of 47143 files ...
#638 of 47143 files ...
#639 of 47143 files ...
#640 of 47143 files ...
#641 of 47143 files ...
#642 of 47143 files ...
#643 of 47143 files ...
#644 of 47143 files ...
#645 of 47143 files ...
#646 of 47143 files ...
#647 of 47143 files ...
#648 of 47143 files ...
#649 of 47143 files ...
#650 of 47143 files ...
#651 of 47143 files ...
#652 of 47143 files ...
#653 of 47143 files ...
#654 of 47143 files ...
#655 of 47143 files ...
#656 of 47143 files ...
#657 of 47143 files ...
#658 of 47143 files ...
#659 of 47143 files ...
#660 of 47143 files ...
#661 of 47143 files ...
#662 of 47143 files ...
#663 of 47143 files ...
#664 of 47143 files ...
#665 of 47143 files ...
#666 of 47143 files ...
#667 of 47143 files ...
#668 of 47143 files ...
#669 of 47143 files ...
#670 of 47143 files ...
#671 of 47143 files ...
#672 of 47143 files ...
#673 of 47143 files ...
#674 of 47143 files ...
#675 of 47143 files ...
#676 of 47143 files ...
#677 of 47143 files ...
#678 of 47143 files ...
#679 of 47143 files ...
#680 of 47143 files ...
#681 of 47143 files ...
#682 of 47143 files ...
#683 of 47143 files ...
#684 of 47143 files ...
#685 of 47143 files ...
#686 of 47143 files ...
#687 of 47143 files ...
#688 of 47143 files ...
#689 of 47143 files ...
#690 of 47143 files ...
#691 of 47143 files ...
#692 of 47143 files ...
#693 of 47143 files ...
#694 of 47143 files ...
#695 of 47143 files ...
#696 of 47143 files ...
#697 of 47143 files ...
#698 of 47143 files ...
#699 of 47143 files ...
#700 of 47143 files ...
#701 of 47143 files ...
#702 of 47143 files ...
#703 of 47143 files ...
#704 of 47143 files ...
#705 of 47143 files ...
#706 of 47143 files ...
#707 of 47143 files ...
#708 of 47143 files ...
#709 of 47143 files ...
#710 of 47143 files ...
#711 of 47143 files ...
#712 of 47143 files ...
#713 of 47143 files ...
#714 of 47143 files ...
#715 of 47143 files ...
#716 of 47143 files ...
#717 of 47143 files ...
#718 of 47143 files ...
#719 of 47143 files ...
#720 of 47143 files ...
#721 of 47143 files ...
#722 of 47143 files ...
#723 of 47143 files ...
#724 of 47143 files ...
#725 of 47143 files ...
#726 of 47143 files ...
#727 of 47143 files ...
#728 of 47143 files ...
#729 of 47143 files ...
#730 of 47143 files ...
#731 of 47143 files ...
#732 of 47143 files ...
#733 of 47143 files ...
#734 of 47143 files ...
#735 of 47143 files ...
#736 of 47143 files ...
#737 of 47143 files ...
#738 of 47143 files ...
#739 of 47143 files ...
#740 of 47143 files ...
#741 of 47143 files ...
#742 of 47143 files ...
#743 of 47143 files ...
#744 of 47143 files ...
#745 of 47143 files ...
#746 of 47143 files ...
#747 of 47143 files ...
#748 of 47143 files ...
#749 of 47143 files ...
#750 of 47143 files ...
#751 of 47143 files ...
#752 of 47143 files ...
#753 of 47143 files ...
#754 of 47143 files ...
#755 of 47143 files ...
#756 of 47143 files ...
#757 of 47143 files ...
#758 of 47143 files ...
#759 of 47143 files ...
#760 of 47143 files ...
#761 of 47143 files ...
#762 of 47143 files ...
#763 of 47143 files ...
#764 of 47143 files ...
#765 of 47143 files ...
#766 of 47143 files ...
#767 of 47143 files ...
#768 of 47143 files ...
#769 of 47143 files ...
#770 of 47143 files ...
#771 of 47143 files ...
#772 of 47143 files ...
#773 of 47143 files ...
#774 of 47143 files ...
#775 of 47143 files ...
#776 of 47143 files ...
#777 of 47143 files ...
#778 of 47143 files ...
#779 of 47143 files ...
#780 of 47143 files ...
#781 of 47143 files ...
#782 of 47143 files ...
#783 of 47143 files ...
#784 of 47143 files ...
#785 of 47143 files ...
#786 of 47143 files ...
#787 of 47143 files ...
#788 of 47143 files ...
#789 of 47143 files ...
#790 of 47143 files ...
#791 of 47143 files ...
#792 of 47143 files ...
#793 of 47143 files ...
#794 of 47143 files ...
#795 of 47143 files ...
#796 of 47143 files ...
#797 of 47143 files ...
#798 of 47143 files ...
#799 of 47143 files ...
#800 of 47143 files ...
#801 of 47143 files ...
#802 of 47143 files ...
#803 of 47143 files ...
#804 of 47143 files ...
#805 of 47143 files ...
#806 of 47143 files ...
#807 of 47143 files ...
#808 of 47143 files ...
#809 of 47143 files ...
#810 of 47143 files ...
#811 of 47143 files ...
#812 of 47143 files ...
#813 of 47143 files ...
#814 of 47143 files ...
#815 of 47143 files ...
#816 of 47143 files ...
#817 of 47143 files ...
#818 of 47143 files ...
#819 of 47143 files ...
#820 of 47143 files ...
#821 of 47143 files ...
#822 of 47143 files ...
#823 of 47143 files ...
#824 of 47143 files ...
#825 of 47143 files ...
#826 of 47143 files ...
#827 of 47143 files ...
#828 of 47143 files ...
#829 of 47143 files ...
#830 of 47143 files ...
#831 of 47143 files ...
#832 of 47143 files ...
#833 of 47143 files ...
#834 of 47143 files ...
#835 of 47143 files ...
#836 of 47143 files ...

,Target,RA,DEC,Distance (pc),Cadence ID,Cadence Type,Receiver,Vmag,Spectral Type,.h5 path 1,...,.h5 path 3,.h5 path 4,.h5 path 5,.h5 path 6,.dat path 1,.dat path 2,.dat path 3,.dat path 4,.dat path 5,.dat path 6
0,GJ1002,0 6 42.9,-7 32 51,4.69,3635,ABACAD,Rcvr1_2,13.7,M5.0V,/datag/pipeline/AGBT16A_999_219/holding/splice...,...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
1,GJ1002,0 6 42.9,-7 32 51,4.69,9642,ABACAD,Rcvr2_3,13.7,M5.0V,/datag/pipeline/AGBT16B_999_18/holding/spliced...,...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
2,GJ1002,0 6 42.9,-7 32 51,4.69,9642,ABACAD,Rcvr2_3,13.7,M5.0V,/datag/pipeline/AGBT16B_999_18/holding/spliced...,...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
3,GJ1002,0 6 42.9,-7 32 51,4.69,12847,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT16B_999_82/collate/spliced...,...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
4,GJ1002,0 6 42.9,-7 32 51,4.69,423617,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47138,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
47139,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
47140,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
47141,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
47142,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...

In [10]:
dfc.to_csv('/datax/scratch/benjb/bl_nearby_stars/BL_nearby_star_sample_cadences.csv', index=False)