In [6]:
import numpy as np 
import matplotlib.pyplot as plt 
import glob
import os
import pandas as pd
from turbo_seti.find_event.find_event_pipeline import find_event_pipeline
from turbo_seti.find_event.plot_event_pipeline import plot_event_pipeline
import multiprocessing
import logging

In [ ]:
df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/all_events.csv')

In [ ]:
# outdir = '/datax/scratch/benjb/bl_nearby_stars/seticore_output/within_5.1_pc/'

# df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/unique_star_cadences_catalog_within_5.1_pc_no_band.csv')
# h5list = df['.h5 path'].values

# dfr = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/star_cadences_catalog_with_receiver.csv')

# rcvrlist = dfr['Receiver'].values

# rcvrvec = []

# for h5 in h5list:
#     rcvrs = rcvrlist[np.where(dfr['.h5 path'].values == h5)[0]]
#     rcvr = np.unique(rcvrs)[0]
#     rcvrvec.append(rcvr)

# rcvrvec = np.array(rcvrvec)

# df2 = pd.DataFrame({'Receiver': rcvrvec})
# dfn = df.join(df2)

# datlist = []

# for h5 in h5list:
#     basename = os.path.basename(h5)
#     dat = outdir + basename[:-2] + 'dat'
#     datlist.append(dat)

# dff = df.join(pd.DataFrame({'.dat path': datlist})).join(df2)

# dff.to_csv('/datax/scratch/benjb/bl_nearby_stars/star_cadences_catalog.csv')

In [2]:
df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/BL_cadences_unique_nearby_star_sample_only.csv')
df

,Target,RA,DEC,Distance (pc),Cadence ID,Cadence Type,Receiver,Vmag,Spectral Type,.h5 path 1,...,.h5 path 3,.h5 path 4,.h5 path 5,.h5 path 6,.dat path 1,.dat path 2,.dat path 3,.dat path 4,.dat path 5,.dat path 6
0,GJ1002,0 6 42.9,-7 32 51,4.69,3635,ABACAD,Rcvr1_2,13.7,M5.0V,/datag/pipeline/AGBT16A_999_219/holding/splice...,...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datag/pipeline/AGBT16A_999_219/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
1,GJ1002,0 6 42.9,-7 32 51,4.69,9642,ABACAD,Rcvr2_3,13.7,M5.0V,/datag/pipeline/AGBT16B_999_18/holding/spliced...,...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datag/pipeline/AGBT16B_999_18/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
2,GJ1002,0 6 42.9,-7 32 51,4.69,12847,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT16B_999_82/collate/spliced...,...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datag/pipeline/AGBT16B_999_82/collate/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
3,GJ1002,0 6 42.9,-7 32 51,4.69,423617,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
4,GJ1002,0 6 42.9,-7 32 51,4.69,423617,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT23B_999_31/blc02_blp02/blc...,...,/datag/pipeline/AGBT23B_999_31/blc02_blp02/blc...,/datag/pipeline/AGBT23B_999_31/blc02_blp02/blc...,/datag/pipeline/AGBT23B_999_31/blc02_blp02/blc...,/datag/pipeline/AGBT23B_999_31/blc02_blp02/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39172,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc72_blp32/blc...,...,/datag/pipeline/AGBT23B_999_14/blc72_blp32/blc...,/datag/pipeline/AGBT23B_999_14/blc72_blp32/blc...,/datag/pipeline/AGBT23B_999_14/blc72_blp32/blc...,/datag/pipeline/AGBT23B_999_14/blc72_blp32/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
39173,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
39174,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
39175,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
39176,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...

In [9]:
dfh = df.iloc[np.where((df['Target'].values == 'HIP4849') & (df['Receiver'].values == 'Rcvr8_10'))[0]]
for i, h5 in enumerate(dfh['.h5 path 1']):
    print(dfh['Cadence ID'].values[i], h5)

30515 /datag/pipeline/AGBT18B_999_09/blc40/blc00_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc41/blc01_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc42/blc02_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc43/blc03_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc44/blc04_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc45/blc05_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc46/blc06_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc50/blc10_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc47/blc07_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc51/blc11_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc52/blc12_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc53/blc13_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc54/blc14_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc55/blc15_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc56/blc16_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc60/blc20_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc57/blc17_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc61/blc21_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc62/blc22_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc63/blc23_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc64/blc24_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc65/blc25_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc66/blc26_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
33164 /datag/pipeline/AGBT18B_999_48/collate1/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58417_30809_HIP4849_0063.gpuspec.0000.h5
33773 /datag/pipeline/AGBT18B_999_55/holding/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58429_28764_HIP4849_0063.gpuspec.0000.h5
34376 /datag/pipeline/AGBT18B_999_65/holding/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58440_26177_HIP4849_0063.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp00/blc40_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp01/blc41_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp02/blc42_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp03/blc43_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp04/blc44_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp05/blc45_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp06/blc46_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp10/blc50_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp07/blc47_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp11/blc51_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp12/blc52_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp13/blc53_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp14/blc54_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp15/blc55_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp16/blc56_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp20/blc60_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp17/blc57_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp21/blc61_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp22/blc62_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp23/blc63_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp24/blc64_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp25/blc65_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp26/blc66_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp00/blc40_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp01/blc41_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp02/blc42_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp03/blc43_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp04/blc44_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp05/blc45_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp06/blc46_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp10/blc50_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp07/blc47_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp11/blc51_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp12/blc52_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp13/blc53_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp14/blc54_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp15/blc55_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp16/blc56_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp20/blc60_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp17/blc57_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp21/blc61_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp22/blc62_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp23/blc63_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp24/blc64_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp25/blc65_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp26/blc66_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35904 /datag/pipeline/AGBT18B_999_87/holding/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58481_08170_HIP4849_0035.gpuspec.0000.h5
36216 /datag/pipeline/AGBT18B_999_90/collate2/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58486_06278_HIP4849_0100.gpuspec.0000.h5
36422 /datag/pipeline/AGBT18B_999_92/collate1/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58493_14747_HIP4849_0068.gpuspec.0000.h5

In [7]:
df.iloc[np.where(df['Cadence Type'].values == 'ABABAB')[0]]

,Target,RA,DEC,Distance (pc),Cadence ID,Cadence Type,Receiver,Vmag,Spectral Type,.h5 path 1,...,.h5 path 3,.h5 path 4,.h5 path 5,.h5 path 6,.dat path 1,.dat path 2,.dat path 3,.dat path 4,.dat path 5,.dat path 6
11950,HIP25110,5 22 33.0,79 13 54,20.9,29635,ABABAB,Rcvr8_10,5.08,F6V,/datag/pipeline/AGBT18A_999_92/collate/spliced...,...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11951,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11952,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11953,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11954,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36599,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36600,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36601,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36602,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36603,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...

In [4]:
df.iloc[np.where(df['Cadence Type'].values == 'None')[0]]

,Target,RA,DEC,Distance (pc),Cadence ID,Cadence Type,Receiver,Vmag,Spectral Type,.h5 path 1,...,.h5 path 3,.h5 path 4,.h5 path 5,.h5 path 6,.dat path 1,.dat path 2,.dat path 3,.dat path 4,.dat path 5,.dat path 6
204,GJ166,4 15 13.8,-7 40 4,4.98,6646,None,Rcvr1_2,4.43,K0.5V,/datag/pipeline/AGBT16A_999_77/holding/spliced...,...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
363,GJ280,7 39 17.3,5 13 13,3.50,6380,None,Rcvr1_2,0.37,F5IV,/datag/pipeline/AGBT16A_999_66/holding/spliced...,...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
401,GJ388,10 19 35.8,19 52 9,4.88,1132,None,Rcvr1_2,9.29,M2.5V,/datag/pipeline/AGBT16A_999_140/collate/splice...,...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
402,GJ388,10 19 35.8,19 52 9,4.88,1543,None,Rcvr1_2,9.29,M2.5V,/datag/pipeline/AGBT16A_999_154/holding/splice...,...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
404,GJ388,10 19 35.8,19 52 9,4.88,1549,None,Rcvr1_2,9.29,M2.5V,/datag/pipeline/AGBT16A_999_154/holding/splice...,...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38498,HIP9884,2 7 10.6,23 27 42,20.20,1007,None,Rcvr1_2,2.01,K2III,/datag/pipeline/AGBT16A_999_136/holding/splice...,...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
38500,HIP9884,2 7 10.6,23 27 42,20.20,1013,None,Rcvr1_2,2.01,K2III,/datag/pipeline/AGBT16A_999_136/holding/splice...,...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
38528,HIP98906,20 5 0.05,54 25 48,15.80,6090,None,Rcvr2_3,11.90,M3,/datag/pipeline/AGBT16A_999_53/holding/spliced...,...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
38614,HIP99031,20 6 21.4,35 58 13,24.10,6823,None,Rcvr1_2,5.38,K0IV,/datag/pipeline/AGBT16A_999_83/holding/spliced...,...,/datag/pipeline/AGBT16A_999_83/holding/spliced...,/datag/pipeline/AGBT16A_999_83/holding/spliced...,/datag/pipeline/AGBT16A_999_83/holding/spliced...,/datag/pipeline/AGBT16A_999_83/collate/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
39079,LHS292,10 48 13.2,-11 20 38,4.53,1613,None,Rcvr1_2,15.70,M6.5V,/datag/pipeline/AGBT16A_999_157/holding/splice...,...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...

In [ ]:
'''full_target_list = df['Target'].values
full_cadence_id_list = df['Cadence ID'].values
full_receiver_list = df['Receiver'].values
for i in range(len(full_target_list)):
    cadences = full_cadence_id_list[i:i+1]
    receivers = np.unique(full_receiver_list[i:i+1])
    targets = []
    for j in range(6):
        t = df['.h5 path 1'].values[i+j].split('guppi_')[1][12:-21]
        if len(t) < 3:
            t = df['.h5 path 1'].values[i+j].split('guppi_')[1][6:-21] # account for GJ15B cadence listed with only integer MJD
        targets.append(t.upper()) # some stars not recorded in all uppercase

    odd_targets = np.unique(targets[::2])
    even_targets = np.unique(targets[1::2])
    cadence_type = 'None'
    for t in odd_targets:
        if 'OFF' in t:
            if len(even_targets) == 1:
                cadence_type = 'BACADA'
    for t in even_targets:
        if 'OFF' in t:
            if len(odd_targets) == 1:
                cadence_type = 'ABACAD'
    if cadence_type == 'None':
        n_odd_ons = len(np.unique(targets[::2]))
        n_even_ons = len(np.unique(targets[1::2]))
        if (n_odd_ons == 1) & (n_even_ons == 1):
            cadence_type = 'ABABAB'
        if (n_odd_ons == 1) & (n_even_ons != 1):
            cadence_type = 'ABACAD'
        if (n_odd_ons != 1) & (n_even_ons == 1):
            cadence_type = 'BACADA'
    if cadence_type == 'ABABAB':
        print(cadence_type, receivers, targets)
    
    # print(cadences)
    # print(targets)
    if i > 10:
        break
'''

In [ ]:
print(np.unique(df['Receiver'].values))

In [ ]:
### The full run on all data must include the following:

### - check for ABACAD vs BACADA

### - check that all 'ON' pointings are the same target even if not named exactly the same
### ----- e.g. GJ1245AC vs GJ1245B
### THIS IS OKAY — IF NAMED SEPARATELY, THEY ARE FAR ENOUGH APART NOT TO BE SEARCHED SIMULTANEOUSLY

### - check for band and only retain hits from proper sensitivity range
### ----- this will be hard for X-band, where the new receiver requires checking for number of banks

### DONE WITH THE ABOVE
### Now need to implement this with multiprocessing.

In [ ]:
full_target_list = df['Target'].values
full_cadence_id_list = df['Cadence ID'].values
full_h5_list_1 = df['.h5 path 1'].values
full_h5_list_2 = df['.h5 path 2'].values
full_h5_list_3 = df['.h5 path 3'].values
full_h5_list_4 = df['.h5 path 4'].values
full_h5_list_5 = df['.h5 path 5'].values
full_h5_list_6 = df['.h5 path 6'].values
full_dat_list_1 = df['.dat path 1'].values
full_dat_list_2 = df['.dat path 2'].values
full_dat_list_3 = df['.dat path 3'].values
full_dat_list_4 = df['.dat path 4'].values
full_dat_list_5 = df['.dat path 5'].values
full_dat_list_6 = df['.dat path 6'].values
full_receiver_list = df['Receiver'].values

data_loc = '/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent'

start_counter = 0

In [ ]:
logger = logging.getLogger(__name__)

reached_here_list = [
    173,  #0
    1264, #1
    1264, #2
    1264, #3
    1264, #4
    1264, #5 
    1264, #6
    1264, #7
    1264, #8
    1264, #9
    1264, #10
    1264, #11
    1264, #12
    1264, #13
    1063, #14
    1264, #15
    1264, #16
    1264, #17
    1026, #18
    1264, #19
    1264, #20
    1264, #21
    1264, #22
    1264, #23
    1264, #24
    1264, #25
    1264, #26
    1264, #27
    1264, #28
    1264, #29
    1032, #30
    1264  #31
]

def process_files(xxx):
    n = int(xxx[0])
    df0 = xxx[1]
    cutoff = reached_here_list[int(n)]
    batch_h5_list_1 = df0['.h5 path 1'].values
    batch_h5_list_2 = df0['.h5 path 2'].values
    batch_h5_list_3 = df0['.h5 path 3'].values
    batch_h5_list_4 = df0['.h5 path 4'].values
    batch_h5_list_5 = df0['.h5 path 5'].values
    batch_h5_list_6 = df0['.h5 path 6'].values
    batch_dat_list_1 = df0['.dat path 1'].values
    batch_dat_list_2 = df0['.dat path 2'].values
    batch_dat_list_3 = df0['.dat path 3'].values
    batch_dat_list_4 = df0['.dat path 4'].values
    batch_dat_list_5 = df0['.dat path 5'].values
    batch_dat_list_6 = df0['.dat path 6'].values
    cadence_id_list = df0['Cadence ID'].values
    target_list = df0['Target'].values
    receiver_list = df0['Receiver'].values
    # Remove all handlers associated with the root logger object.
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)
    logging.basicConfig(filename=f'{data_loc}/000_{n}_060225.log', filemode="a", level=logging.DEBUG)


    for i in range(len(batch_h5_list_1)):

        logger.info(f'Searching #{i+1} of {len(batch_h5_list_1)} files ...')

        #if i+1 < cutoff:
        #    print('Already searched this file; continuing ...')
        #    continue
        if n*1263+i+1 == 172:
            continue

        # for each set of 6 files, run FindEvent and PlotEvent

        h5_list = np.array([
            batch_h5_list_1[i],
            batch_h5_list_2[i],
            batch_h5_list_3[i],
            batch_h5_list_4[i],
            batch_h5_list_5[i],
            batch_h5_list_6[i],
            ])
        dat_list = np.array([
            batch_dat_list_1[i],
            batch_dat_list_2[i],
            batch_dat_list_3[i],
            batch_dat_list_4[i],
            batch_dat_list_5[i],
            batch_dat_list_6[i],
            ])

        # check that all h5 files in cadence exist and were searched
        # (not true for 3 files, 5 occurrences)
        if 'None' in dat_list:
            continue

        target = target_list[i]
        cadence_id = cadence_id_list[i]
        receiver = receiver_list[i]
        s = dat_list[0].split('blc')
        if ('spliced' in dat_list[0]) & (s[1][2] == '_'):
            node = 'blc'+s[1][:2]
        else:
            node = os.path.basename(batch_h5_list_1[i])[:5]

        # This block checks the cadence type:
        # Either ABACAD, BACADA, or None (if not a real cadence).
        # ABABAB is also checked, but does not occur in this dataset.
        #cadences = full_cadence_id_list[6*i:6*i+6]
        #receivers = np.unique(full_receiver_list[6*i:6*i+6])
        targets = []
        for j in range(6):
            t = h5_list[j].split('guppi_')[1][12:-21]
            if len(t) < 3:
                t = h5_list.split('guppi_')[1][6:-21] # account for GJ15B cadence listed with only integer MJD
            targets.append(t.upper()) # some stars not recorded in all uppercase
        odd_targets = np.unique(targets[::2])
        even_targets = np.unique(targets[1::2])
        cadence_type = 'None'
        off_check = 0
        for t in odd_targets:
            if 'OFF' in t:
                if len(even_targets) == 1:
                    cadence_type = 'BACADA'
                off_check += 1
        for t in even_targets:
            if 'OFF' in t:
                if len(odd_targets) == 1:
                    cadence_type = 'ABACAD'
                off_check += 1
        if (cadence_type == 'None') & (off_check == 0):
            n_odd_ons = len(np.unique(targets[::2]))
            n_even_ons = len(np.unique(targets[1::2]))
            if (n_odd_ons == 1) & (n_even_ons == 1):
                cadence_type = 'ABABAB'
            if (n_odd_ons == 1) & (n_even_ons != 1):
                cadence_type = 'ABACAD'
            if (n_odd_ons != 1) & (n_even_ons == 1):
                cadence_type = 'BACADA'

        #if not cadence_id == 4051:
        #    continue
        if cadence_type == 'ABACAD':
            target = targets[0]
        elif cadence_type == 'BACADA':
            target = targets[1]

        logger.info(f'{cadence_id} {cadence_type} {target} {receiver} {targets}')

        if cadence_type == 'ABACAD':
            continue
        if cadence_type == 'BACADA':
            continue
        if cadence_type == 'None':
            continue

        print(node)
        print(dat_list[0])

        # if (target == 'GJ412B') & (node == 'blc04') & (receiver == 'Rcvr1_2'):
        #     start_counter += 1
        
        # if start_counter == 0:
        #     continue


        on_or_off = 'None'

        if cadence_type == 'ABACAD':
            on_or_off = 'ON'
        elif cadence_type == 'BACADA':
            on_or_off = 'OFF'

        for k, on_or_off in enumerate(['ON', 'OFF']):
            
            target = targets[k]

            csvf_path = f'{data_loc}/{n*1263+i}_{cadence_id}_{target}_{receiver}_{node}_found_event_table_3.csv'

            h5_list_path = os.path.join(data_loc, f'{n*1263+i}_{cadence_id}_{target}_{receiver}_{node}_h5_files.lst')
            with open(h5_list_path, 'w') as f:
                for h5_path in h5_list:
                    f.write(h5_path + '\n')

            dat_list_path = os.path.join(data_loc, f'{n*1263+i}_{cadence_id}_{target}_{receiver}_{node}_dat_files.lst')
            with open(dat_list_path, 'w') as f:
                for dat_path in dat_list:
                    f.write(dat_path + '\n')

            find_event_pipeline(dat_list_path, 
                            h5_list_path,
                            #SNR_cut=2,
                            check_zero_drift = True,
                            filter_threshold = 3, 
                            on_off_first = on_or_off,
                            number_in_cadence = len(dat_list),
                            csv_name=csvf_path, 
                            saving=True
                            )
            
            if not os.path.exists(csvf_path):
                logger.info('No event CSV found. Continuing ...')
                continue

            # trimming regions of insensitivity
            event_df = pd.read_csv(csvf_path)
            if receiver == 'Rcvr1_2':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 1100) & (event_df['Freq'].values < 1200) |
                            (event_df['Freq'].values > 1340) & (event_df['Freq'].values < 1900))[0]
                    ]
            elif receiver == 'Rcvr2_3':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 1800) & (event_df['Freq'].values < 2300) |
                            (event_df['Freq'].values > 2360) & (event_df['Freq'].values < 2700))[0]
                    ]
            elif receiver == 'Rcvr4_6':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 4000) & (event_df['Freq'].values < 7800))[0]
                    ]
            elif receiver == 'Rcvr8_10':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 7800) & (event_df['Freq'].values < 11200))[0]
                    ]
            elif receiver == 'Rcvr8_10_NEW':
                # sensitivity range for new X-band receiver is, like for the old receiver,
                # determined by the range where Tsys < 50 K
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 7550) & (event_df['Freq'].values < 11700))[0]
                    ]
            
            trimmed_event_df.dropna(subset=['in_n_ons'], inplace=True)

            trimmed_event_df.to_csv(f'{data_loc}/{n*1263+i}_{cadence_id}_{target}_{receiver}_{node}_f3_trimmed.csv')
            tcsvf_path = f'{data_loc}/{cadence_id}_{target}_{receiver}_{node}_f3_trimmed.csv'
            
            # if len(trimmed_event_df) > 0:
            #     plot_event_pipeline(tcsvf_path, # full path of the CSV file built by find_event_pipeline()
            #             h5_list_path, # full path of text file containing the list of .h5 files
            #             filter_spec='f{}'.format(3), # filter threshold
            #             user_validation=False, # Non-interactive
            #             plot_dir=data_loc+'/pngs/')

In [ ]:
'''h5lst_list = []

for i in range(len(full_h5_list_1)):

    #print(f'Testing #{i+1} of {len(full_h5_list)//6} files ...')

    # for each set of 6 files, run FindEvent and PlotEvent

    h5_list = np.array([
            full_h5_list_1[i],
            full_h5_list_2[i],
            full_h5_list_3[i],
            full_h5_list_4[i],
            full_h5_list_5[i],
            full_h5_list_6[i],
            ])
    dat_list = np.array([
            full_dat_list_1[i],
            full_dat_list_2[i],
            full_dat_list_3[i],
            full_dat_list_4[i],
            full_dat_list_5[i],
            full_dat_list_6[i],
            ])

    # check that all h5 files in cadence exist and were searched
    # (not true for 3 files, 5 occurrences)
    if 'None' in dat_list:
        continue

    target = full_target_list[i]
    cadence_id = full_cadence_id_list[i]
    receiver = full_receiver_list[i]
    s = dat_list[0].split('blc')
    if ('spliced' in dat_list[0]) & (s[1][2] == '_'):
        node = 'blc'+s[1][:2]
    else:
        node = os.path.basename(full_h5_list_1[i])[:5]

    # This block checks the cadence type:
    # Either ABACAD, BACADA, or None (if not a real cadence).
    # ABABAB is also checked, but does not occur in this dataset.
    #cadences = full_cadence_id_list[6*i:6*i+6]
    #receivers = np.unique(full_receiver_list[6*i:6*i+6])
    targets = []
    for j in range(6):
        t = h5_list[j].split('guppi_')[1][12:-21]
        if len(t) < 3:
            t = h5_list[j].split('guppi_')[1][6:-21] # account for GJ15B cadence listed with only integer MJD
        targets.append(t.upper()) # some stars not recorded in all uppercase
    odd_targets = np.unique(targets[::2])
    even_targets = np.unique(targets[1::2])
    cadence_type = 'None'
    off_check = 0
    for t in odd_targets:
        if 'OFF' in t:
            if len(even_targets) == 1:
                cadence_type = 'BACADA'
            off_check += 1
    for t in even_targets:
        if 'OFF' in t:
            if len(odd_targets) == 1:
                cadence_type = 'ABACAD'
            off_check += 1
    if (cadence_type == 'None') & (off_check == 0):
        n_odd_ons = len(np.unique(targets[::2]))
        n_even_ons = len(np.unique(targets[1::2]))
        if (n_odd_ons == 1) & (n_even_ons == 1):
            cadence_type = 'ABABAB'
        if (n_odd_ons == 1) & (n_even_ons != 1):
            cadence_type = 'ABACAD'
        if (n_odd_ons != 1) & (n_even_ons == 1):
            cadence_type = 'BACADA'

    #if not cadence_id == 4051:
    #    continue
    if cadence_type == 'ABACAD':
        target = targets[0]
    elif cadence_type == 'BACADA':
        target = targets[1]

    #print(f'{cadence_id} {cadence_type} {target} {receiver} {targets}')

    if cadence_type == 'None':
        continue

    #print(node)
    #print(dat_list[0])

    # if (target == 'GJ412B') & (node == 'blc04') & (receiver == 'Rcvr1_2'):
    #     start_counter += 1
    
    # if start_counter == 0:
    #     continue

    h5_list_path = os.path.join(data_loc, f'{cadence_id}_{target}_{receiver}_{node}_h5_files.lst')
    h5lst_list.append(h5_list_path)
    if h5_list_path == '/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/5152_HIP42438_Rcvr1_2_splic_h5_files.lst':
        for j in h5_list:
            print(i, j)
'''

In [ ]:
#u, c = np.unique(h5lst_list, return_counts=True)
#print(len(h5lst_list))
#print(len(u))

In [ ]:
#for i in u[np.where(c > 1)[0]]:
#    print(i)

In [ ]:
if __name__ == "__main__":
    # Define n+1 sets of files
    # The 1 accounts for the remainder after dividing N/n
    n = 31
    batch_size = len(df)//n
    file_sets = [[str(i), df[i*batch_size:(i+1)*batch_size]] for i in range(n)]
    file_sets.append([str(n), df[n*batch_size:]])

    # Create a pool of n+1 processes
    with multiprocessing.Pool(processes=n+1) as pool:
        # Map the process_files function to each file set
        pool.map(process_files, file_sets)

    print("All files processed.")