In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import glob
import os
import pandas as pd
from turbo_seti.find_event.find_event_pipeline import find_event_pipeline
from turbo_seti.find_event.plot_event_pipeline import plot_event_pipeline
import multiprocessing
import logging

In [ ]:
#df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/all_events.csv')

In [ ]:
# outdir = '/datax/scratch/benjb/bl_nearby_stars/seticore_output/within_5.1_pc/'

# df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/unique_star_cadences_catalog_within_5.1_pc_no_band.csv')
# h5list = df['.h5 path'].values

# dfr = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/star_cadences_catalog_with_receiver.csv')

# rcvrlist = dfr['Receiver'].values

# rcvrvec = []

# for h5 in h5list:
#     rcvrs = rcvrlist[np.where(dfr['.h5 path'].values == h5)[0]]
#     rcvr = np.unique(rcvrs)[0]
#     rcvrvec.append(rcvr)

# rcvrvec = np.array(rcvrvec)

# df2 = pd.DataFrame({'Receiver': rcvrvec})
# dfn = df.join(df2)

# datlist = []

# for h5 in h5list:
#     basename = os.path.basename(h5)
#     dat = outdir + basename[:-2] + 'dat'
#     datlist.append(dat)

# dff = df.join(pd.DataFrame({'.dat path': datlist})).join(df2)

# dff.to_csv('/datax/scratch/benjb/bl_nearby_stars/star_cadences_catalog.csv')

In [2]:
#df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/BL_cadences_unique_nearby_star_sample_only.csv')
#df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/BL_NSS_cadences_turboSETI_symlinks.csv')
df = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/BL_NSS_cadences_turboSETI_BLISS_071326.csv')
df

,Target,RA,DEC,Distance (pc),Cadence ID,Cadence Type,Receiver,Vmag,Spectral Type,.h5 path 1,...,.dat path 4,.dat path 5,.dat path 6,bliss .dat path 1,bliss .dat path 2,bliss .dat path 3,bliss .dat path 4,bliss .dat path 5,bliss .dat path 6,turboSETI event .csv
0,GJ1002,0 6 42.9,-7 32 51,4.69,3635,ABACAD,Rcvr1_2,13.7,M5.0V,/datag/pipeline/AGBT16A_999_219/holding/splice...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
1,GJ1002,0 6 42.9,-7 32 51,4.69,9642,ABACAD,Rcvr2_3,13.7,M5.0V,/datag/pipeline/AGBT16B_999_18/holding/spliced...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
2,GJ1002,0 6 42.9,-7 32 51,4.69,12847,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT16B_999_82/collate/spliced...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,/datax/scratch/benjb/bl_nearby_stars/respliced...,NaN
3,GJ1002,0 6 42.9,-7 32 51,4.69,423617,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT23B_999_31/blc01_blp01/blc...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,NaN
4,GJ1002,0 6 42.9,-7 32 51,4.69,423617,ABACAD,Rcvr4_6,13.7,M5.0V,/datag/pipeline/AGBT23B_999_31/blc02_blp02/blc...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39172,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc72_blp32/blc...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,NaN
39173,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc73_blp33/blc...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,NaN
39174,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc74_blp34/blc...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,NaN
39175,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc75_blp35/blc...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,NaN
39176,SO0253,2 53 4.68,16 51 52,3.85,421558,ABACAD,Rcvr8_10_NEW,15.1,M6.5V,/datag/pipeline/AGBT23B_999_14/blc76_blp36/blc...,...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,/datax/scratch/benjb/bl_nearby_stars/all_bliss...,NaN

In [4]:
bd1 = df['bliss .dat path 1'].values
bd2 = df['bliss .dat path 2'].values
bd3 = df['bliss .dat path 3'].values
bd4 = df['bliss .dat path 4'].values
bd5 = df['bliss .dat path 5'].values
bd6 = df['bliss .dat path 6'].values

h51 = df['.h5 path 1'].values
h52 = df['.h5 path 2'].values
h53 = df['.h5 path 3'].values
h54 = df['.h5 path 4'].values
h55 = df['.h5 path 5'].values
h56 = df['.h5 path 6'].values

# files to search
s1 = h51[bd1.astype(str)=='nan']
s2 = h52[bd2.astype(str)=='nan']
s3 = h53[bd3.astype(str)=='nan']
s4 = h54[bd4.astype(str)=='nan']
s5 = h55[bd5.astype(str)=='nan']
s6 = h56[bd6.astype(str)=='nan']

s_all = np.concatenate([s1, s2, s3, s4, s5, s6])
print(len(s1), len(s2), len(s3), len(s4), len(s5), len(s6))

0 0 0 1 1 1

In [14]:
print(np.where(df['.h5 path 4'].values == '/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_22127_HIP111868_0064.rawspec.0000.h5')[0])

[4355]

In [32]:
print(np.where(df['turboSETI .dat path 6'].values == 'None')[0])

[]

In [46]:
df1 = pd.read_csv('/datax/scratch/benjb/bl_nearby_stars/BL_NSS_cadences_turboSETI_BLISS_062626b.csv')
df1.iloc[196]

Unnamed: 0                                                             196
Unnamed: 0.1                                                           196
Unnamed: 0.1.1                                                         196
Target                                                               GJ15B
RA                                                              0 18 29.7
DEC                                                               44 1 44
Distance (pc)                                                         3.57
Cadence ID                                                          420941
Cadence Type                                                        ABACAD
Receiver                                                      Rcvr8_10_NEW
Vmag                                                                  11.0
Spectral Type                                                        M3.5V
.h5 path 1               /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc...
.h5 path 2               /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc...
.h5 path 3               /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc...
.h5 path 4               /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc...
.h5 path 5               /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc...
.h5 path 6               /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc...
turboSETI .dat path 1    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 2    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 3    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 4    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 5    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 6    /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 1              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 2              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 3              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 4              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 5              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 6              /datax/scratch/benjb/bl_nearby_stars/seticore_...
bliss .dat path 1        /datax/scratch/benjb/bl_nearby_stars/all_bliss...
bliss .dat path 2        /datax/scratch/benjb/bl_nearby_stars/all_bliss...
bliss .dat path 3        /datax/scratch/benjb/bl_nearby_stars/all_bliss...
bliss .dat path 4        /datax/scratch/benjb/bl_nearby_stars/all_bliss...
bliss .dat path 5        /datax/scratch/benjb/bl_nearby_stars/all_bliss...
bliss .dat path 6        /datax/scratch/benjb/bl_nearby_stars/all_bliss...
turboSETI event .csv                                                   NaN
Name: 196, dtype: object

In [64]:
c = 0
mismatch_idx = []
for i in range(len(df)):
    mjd_h5 = os.path.basename(df['.h5 path 1'].values[i]).split('guppi_')[1][:11]
    mjd_dat = os.path.basename(df['bliss .dat path 1'].values[i]).split('guppi_')[1][:11]
    blc_h5 = os.path.basename(df['.h5 path 1'].values[i]).split('_guppi_')[0][-5:]
    blc_dat = os.path.basename(df['bliss .dat path 1'].values[i]).split('_guppi_')[0][-5:]
    if (mjd_h5 != mjd_dat) | (blc_h5 != blc_dat):
        c += 1
        print(f'{c}: False! {mjd_h5} {mjd_dat}')
        print(f"  {df['.h5 path 1'].values[i]}")
        print(f"  {df['bliss .dat path 1'].values[i]}")
        mismatch_idx.append(i)

1: False! 57977_48304 60223_03425
  /datag/pipeline/AGBT17B_999_07/collate0/spliced_blc00010203040506o7o0111213141516o0o1222324252627o0o1323334353637_guppi_57977_48304_GJ144_0021.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/148_1_0_blc01_guppi_60223_03425_GJ15A_0010.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
2: False! 60233_38409 60223_03425
  /datag/pipeline/AGBT23A_999_43/blc43_blp03/blc43_guppi_60233_38409_GJ144_0016.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/152_1_0_blc05_guppi_60223_03425_GJ15A_0010.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
3: False! 60233_38409 60223_03425
  /datag/pipeline/AGBT23A_999_43/blc44_blp04/blc44_guppi_60233_38409_GJ144_0016.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/153_1_0_blc06_guppi_60223_03425_GJ15A_0010.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
4: False! 60277_25288 60231_41210
  /datag/pipeline/AGBT23B_999_08/blc21_blp21/blc21_guppi_60277_25288_GJ15B_0074.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/190_1_0_blc46_guppi_60231_41210_GJ166_0022.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
5: False! 60277_25288 60233_40349
  /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc30_guppi_60277_25288_GJ15B_0074.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/196_1_0_blc46_guppi_60233_40349_GJ166BC_0022.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
6: False! 58440_35810 60224_50695
  /datag/pipeline/AGBT18B_999_65/blc47/blc47_guppi_58440_35810_GJ234_0089.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/266_1_0_blc01_guppi_60224_50695_GJ234_0046.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
7: False! 58440_35810 60224_50695
  /datag/pipeline/AGBT18B_999_65/blc54/blc54_guppi_58440_35810_GJ234_0089.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/270_1_0_blc05_guppi_60224_50695_GJ234_0046.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
8: False! 58440_35810 60224_50695
  /datag/pipeline/AGBT18B_999_65/blc55/blc55_guppi_58440_35810_GJ234_0089.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/271_1_0_blc06_guppi_60224_50695_GJ234_0046.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
9: False! 58684_80323 58684_86136
  /datag/pipeline/AGBT19A_999_67/blc60/blc60_guppi_58684_80323_GJ411_0016.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/628_1_0_blc70_guppi_58684_86136_GJ412A_0034.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
10: False! 60350_66807 60223_21259
  /datag/pipeline/AGBT23B_999_39/blc70_blp30/blc70_guppi_60350_66807_GJ71_0102.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/1090_1_0_blc01_guppi_60223_21259_GJ820A_0064.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
11: False! 60350_66807 60223_21259
  /datag/pipeline/AGBT23B_999_39/blc73_blp33/blc73_guppi_60350_66807_GJ71_0102.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/1094_1_0_blc05_guppi_60223_21259_GJ820A_0064.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
12: False! 60350_66807 60223_21259
  /datag/pipeline/AGBT23B_999_39/blc74_blp34/blc74_guppi_60350_66807_GJ71_0102.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/1095_1_0_blc06_guppi_60223_21259_GJ820A_0064.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
13: False! 58747_31925 58741_78972
  /datag/pipeline/AGBT19B_999_28/blc56/blc56_guppi_58747_31925_HIP10279_0049.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/1977_1_0_blc40_guppi_58741_78972_HIP103650_0115.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
14: False! 58747_31925 58741_78972
  /datag/pipeline/AGBT19B_999_28/blc60/blc60_guppi_58747_31925_HIP10279_0049.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/1978_1_0_blc41_guppi_58741_78972_HIP103650_0115.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
15: False! 58747_31925 58741_78972
  /datag/pipeline/AGBT19B_999_28/blc64/blc64_guppi_58747_31925_HIP10279_0049.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/1983_1_0_blc46_guppi_58741_78972_HIP103650_0115.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
16: False! 58747_31925 58741_78972
  /datag/pipeline/AGBT19B_999_28/blc65/blc65_guppi_58747_31925_HIP10279_0049.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/1984_1_0_blc47_guppi_58741_78972_HIP103650_0115.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
17: False! 58605_28468 59440_32538
  /datag/pipeline/AGBT19A_999_38/blc67/blc67_guppi_58605_28468_HIP107346_0062.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/3298_1_0_blc00_guppi_59440_32538_HIP109378_0016.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
18: False! 58605_28468 59440_32538
  /datag/pipeline/AGBT19A_999_38/blc71/blc71_guppi_58605_28468_HIP107346_0062.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/3299_1_0_blc01_guppi_59440_32538_HIP109378_0016.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
19: False! 58605_28468 59440_32538
  /datag/pipeline/AGBT19A_999_38/blc76/blc76_guppi_58605_28468_HIP107346_0062.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/3304_1_0_blc06_guppi_59440_32538_HIP109378_0016.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
20: False! 60321_02969 59440_32538
  /datag/pipeline/AGBT23B_999_25/blc00_blp00/blc00_guppi_60321_02969_HIP107346_0035.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/3305_1_0_blc07_guppi_59440_32538_HIP109378_0016.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
21: False! 58299_40470 58469_84882
  /datag/pipeline/AGBT18A_999_94/blc17/blc17_guppi_58299_40470_HIP110951_0022.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4317_1_0_blc42_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
22: False! 58299_40470 58469_84882
  /datag/pipeline/AGBT18A_999_94/blc61/blc21_guppi_58299_40470_HIP110951_0022.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4318_1_0_blc43_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
23: False! 58299_40470 58469_84882
  /datag/pipeline/AGBT18A_999_94/blc62/blc22_guppi_58299_40470_HIP110951_0022.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4319_1_0_blc44_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
24: False! 58299_40470 58469_84882
  /datag/pipeline/AGBT18A_999_94/blc63/blc23_guppi_58299_40470_HIP110951_0022.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4320_1_0_blc45_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
25: False! 58299_40470 58469_84882
  /datag/pipeline/AGBT18A_999_94/blc64/blc24_guppi_58299_40470_HIP110951_0022.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4321_1_0_blc46_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
26: False! 58299_40470 58469_84882
  /datag/pipeline/AGBT18A_999_94/blc65/blc25_guppi_58299_40470_HIP110951_0022.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4322_1_0_blc50_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
27: False! 58299_40470 58469_84882
  /datag/pipeline/AGBT18A_999_94/blc66/blc26_guppi_58299_40470_HIP110951_0022.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4323_1_0_blc47_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
28: False! 57535_44934 58469_84882
  /datag/pipeline/AGBT16A_999_205/holding/spliced_blc0001020304050607_guppi_57535_44934_HIP111169_0015.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4324_1_0_blc51_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
29: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc00/blc00_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4325_1_0_blc52_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
30: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc01/blc01_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4326_1_0_blc53_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
31: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc02/blc02_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4327_1_0_blc54_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
32: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc03/blc03_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4328_1_0_blc55_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
33: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc04/blc04_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4329_1_0_blc56_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
34: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc05/blc05_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4330_1_0_blc60_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
35: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc06/blc06_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4331_1_0_blc57_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
36: False! 57798_67405 58469_84882
  /datag/pipeline/AGBT17A_999_05/blc07/blc07_guppi_57798_67405_HIP111169_0182.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4332_1_0_blc61_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
37: False! 58138_72550 58469_84882
  /datag/pipeline/AGBT17B_999_109/collate1/spliced_blc00010203040506o7o0111213141516o7o0212223242526o7o031323334353637_guppi_58138_72550_HIP111169_0020.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4333_1_0_blc62_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
38: False! 60277_21171 58469_84882
  /datag/pipeline/AGBT23B_999_08/blc00_blp00/blc00_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4334_1_0_blc63_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
39: False! 60277_21171 58469_84882
  /datag/pipeline/AGBT23B_999_08/blc01_blp01/blc01_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4335_1_0_blc64_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
40: False! 60277_21171 58469_84882
  /datag/pipeline/AGBT23B_999_08/blc02_blp02/blc02_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4336_1_0_blc65_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
41: False! 60277_21171 58469_84882
  /datag/pipeline/AGBT23B_999_08/blc03_blp03/blc03_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4337_1_0_blc66_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
42: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc04_blp04/blc04_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4338_1_0_blc40_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
43: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc05_blp05/blc05_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4339_1_0_blc41_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
44: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc06_blp06/blc06_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4340_1_0_blc42_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
45: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc10_blp10/blc10_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4341_1_0_blc43_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
46: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc07_blp07/blc07_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4342_1_0_blc44_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
47: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc11_blp11/blc11_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4343_1_0_blc45_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
48: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc12_blp12/blc12_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4344_1_0_blc46_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
49: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc13_blp13/blc13_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4345_1_0_blc50_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
50: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc14_blp14/blc14_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4346_1_0_blc47_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
51: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc15_blp15/blc15_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4347_1_0_blc51_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
52: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc16_blp16/blc16_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4348_1_0_blc52_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
53: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc20_blp20/blc20_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4349_1_0_blc53_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
54: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc17_blp17/blc17_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4350_1_0_blc54_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
55: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc21_blp21/blc21_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4351_1_0_blc55_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
56: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc22_blp22/blc22_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4352_1_0_blc56_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
57: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc23_blp23/blc23_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4353_1_0_blc60_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
58: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc24_blp24/blc24_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4354_1_0_blc57_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
59: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4355_1_0_blc61_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
60: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc26_blp26/blc26_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4356_1_0_blc62_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
61: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc30_blp30/blc30_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4357_1_0_blc63_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
62: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc27_blp27/blc27_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4358_1_0_blc64_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
63: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc31_blp31/blc31_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4359_1_0_blc65_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
64: False! 60277_21171 58475_01427
  /datag/pipeline/AGBT23B_999_08/blc32_blp32/blc32_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4360_1_0_blc66_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
65: False! 60277_21171 58605_44993
  /datag/pipeline/AGBT23B_999_08/blc33_blp33/blc33_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4361_1_0_blc50_guppi_58605_44993_HIP112915_0119.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
66: False! 60277_21171 58605_44993
  /datag/pipeline/AGBT23B_999_08/blc34_blp34/blc34_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4362_1_0_blc51_guppi_58605_44993_HIP112915_0119.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
67: False! 60277_21171 58605_44993
  /datag/pipeline/AGBT23B_999_08/blc35_blp35/blc35_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4363_1_0_blc52_guppi_58605_44993_HIP112915_0119.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
68: False! 60277_21171 58605_44993
  /datag/pipeline/AGBT23B_999_08/blc36_blp36/blc36_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4364_1_0_blc53_guppi_58605_44993_HIP112915_0119.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
69: False! 57515_49875 58605_44993
  /datag/pipeline/AGBT16A_999_179/holding/spliced_blc0001020304050607_guppi_57515_49875_HIP111170_0003.gpuspec.0000.h5
  /datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4365_1_0_blc54_guppi_58605_44993_HIP112915_0119.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
70: False! 57722_86123 58605_44993
  /datag/pipeline/AGBT16B_999_80/holding/spliced_blc1011121314151617_guppi_57722_86123_HIP111170_0021.gpuspec.0000.h5

In [54]:
print(mismatch_idx)

[148, 152, 153, 190, 196, 266, 270, 271, 628, 1090, 1094, 1095, 1977, 1978, 1983, 1984, 3298, 3299, 3304, 3305, 4317, 4318, 4319, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4333, 4334, 4335, 4336, 4337, 4338, 4339, 4340, 4341, 4342, 4343, 4344, 4345, 4346, 4347, 4348, 4349, 4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4361, 4362, 4363, 4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4382, 4383, 4384, 4385, 4386, 4387, 4388, 4389, 4390, 4391, 4392, 4393, 4394, 4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4408, 4409, 4410, 4411, 4412, 4413, 4414, 4415, 4416, 4417, 4418, 4419, 4420, 4421, 4422, 4423, 4424, 4425, 4426, 4427, 4428, 4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4438, 4439, 4440, 4441, 4442, 4443, 4444, 4445, 4446, 4447, 4448, 4449, 4450, 4451, 4452, 4453, 4454, 4462, 4463, 4464, 4465, 4466, 4467, 4468, 4469, 4470, 4471, 4472, 4473, 4474, 4475, 4476, 4477, 4478, 4479, 4480, 4481, 4482, 4483, 4484, 4485, 4486, 4487, 4488, 4489, 4490, 4491, 4492, 4493, 4494, 4495, 4496, 4497, 4498, 4499, 4500, 4501, 4502, 4503, 4504, 4505, 4506, 4507, 4508, 4509, 4510, 4511, 4512, 4513, 4514, 4515, 4516, 4517, 4518, 4519, 4520, 4521, 4522, 4523, 4524, 4525, 4526, 4527, 4528, 4529, 4530, 4531, 4532, 4533, 4534, 4535, 4536, 4537, 4538, 4539, 4540, 4541, 4542, 4543, 4544, 4545, 4546, 4547, 4548, 4549, 4550, 4551, 4552, 4553, 4554, 4555, 4556, 4557, 4558, 4559, 4560, 4561, 4562, 4563, 4564, 4565, 4566, 4567, 4568, 4569, 4570, 4571, 4572, 4573, 4574, 4575, 4576, 4577, 4578, 4579, 6200, 6204, 6205, 6967, 7738, 7744, 7745, 7775, 7779, 7780, 7857, 7861, 7862, 7923, 7927, 7928, 7929, 8300, 8301, 8305, 8306, 8307, 8855, 8860, 9159, 9165, 9510, 9514, 9515, 10053, 10054, 10376, 10807, 10811, 10812, 11303, 11339, 11343, 11344, 11410, 11411, 11416, 11417, 11419, 11420, 11833, 12112, 12162, 12163, 12527, 12664, 12668, 12669, 13173, 13174, 13987, 13988, 13992, 13993, 13994, 14018, 14019, 14022, 14023, 14024, 14025, 14238, 14239, 14414, 15164, 15168, 15169, 15199, 15203, 15204, 15993, 16034, 16038, 16039, 16370, 16374, 16375, 16771, 16901, 16906, 16997, 17109, 17300, 17992, 18475, 18864, 18868, 18869, 19140, 19491, 19573, 19580, 19581, 19771, 19774, 19775, 19776, 19876, 19884, 19885, 19886, 19887, 19888, 19889, 19890, 19891, 19892, 19893, 19894, 19895, 19896, 19897, 19898, 19899, 19900, 19901, 19902, 19903, 19904, 19905, 19906, 19910, 19911, 19912, 19913, 19914, 19915, 19916, 19917, 19918, 19919, 19920, 19921, 19922, 19923, 19924, 19925, 19926, 19927, 19928, 19929, 19930, 19931, 19932, 19933, 19934, 19935, 19936, 19937, 19938, 19939, 19940, 19941, 19942, 19943, 19944, 19945, 19946, 19947, 19948, 19949, 19950, 19951, 19952, 19953, 19954, 19955, 19959, 19960, 19961, 19962, 19963, 19964, 19965, 19966, 19967, 19968, 19969, 19970, 19971, 19972, 19973, 19974, 19975, 19976, 19977, 19978, 19979, 19980, 19981, 19982, 19983, 19984, 19985, 19986, 19987, 19990, 19991, 19992, 19993, 19994, 19995, 19996, 19997, 19998, 19999, 20000, 20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008, 20009, 20010, 20011, 20012, 20013, 20014, 20015, 20016, 20017, 20018, 20019, 20020, 20021, 20022, 20023, 20024, 20025, 20026, 20027, 20028, 20029, 20030, 20031, 20032, 20033, 20034, 20035, 20036, 20037, 20038, 20039, 20040, 20041, 20042, 20043, 20044, 20045, 20046, 20047, 20054, 20055, 20056, 20057, 20058, 20059, 20060, 20061, 20062, 20063, 20064, 20065, 20066, 20067, 20068, 20069, 20070, 20071, 20072, 20073, 20074, 20075, 20077, 20078, 20079, 20080, 20081, 20082, 20083, 20084, 20085, 20086, 20087, 20088, 20089, 20090, 20091, 20092, 20093, 20094, 20095, 20096, 20097, 20098, 20099, 20100, 20101, 20102, 20103, 20104, 20105, 20106, 20107, 20108, 20109, 20110, 20111, 20112, 20113, 20114, 20115, 20116, 20117, 20118, 20119, 20120, 20121, 20122, 20123, 20124, 20125, 20126, 20127, 20128, 20129, 20130, 20131, 20132, 20133, 20134, 20135, 20136, 20138, 20139, 20140, 20141, 20142, 20143, 20144, 20145, 20146, 20147, 20148, 20149, 20150, 20151, 20152, 20153, 20154, 20155, 20156, 20157, 20158, 20159, 20160, 20161, 20162, 20163, 20164, 20165, 20166, 20181, 20182, 20183, 20184, 20185, 20186, 20187, 20188, 20189, 20190, 20778, 20779, 20780, 20781, 20782, 20783, 20784, 20785, 20786, 20787, 20788, 20789, 20790, 20791, 20792, 20793, 20794, 20795, 20796, 20797, 20798, 20799, 20800, 20807, 20808, 20809, 20810, 20811, 20812, 20813, 20814, 20815, 20816, 20817, 20818, 20819, 20820, 20821, 20822, 20823, 20824, 20825, 20826, 20827, 20828, 20829, 20833, 20834, 20835, 20836, 20837, 20838, 20839, 20840, 20841, 20842, 20843, 20844, 20845, 20846, 20847, 20848, 20849, 20850, 20851, 20852, 20853, 20854, 20855, 20856, 20857, 21337, 21341, 21342, 21429, 21430, 21431, 21432, 21433, 21438, 21439, 21514, 21518, 21519, 21553, 21554, 21570, 21571, 21572, 21930, 21931, 21932, 21933, 21934, 21935, 21936, 21937, 21938, 21939, 21940, 21941, 21942, 21943, 21945, 21946, 21947, 21948, 21949, 21950, 21951, 21952, 21954, 21955, 21956, 21957, 21958, 21959, 21960, 21961, 21962, 21963, 21964, 21965, 21966, 21967, 21968, 21969, 21970, 21971, 21972, 21973, 21974, 21975, 21976, 21977, 21978, 21979, 21980, 21981, 21982, 21983, 21984, 21985, 21986, 21987, 21988, 21989, 21990, 21991, 21992, 21993, 21994, 21995, 21996, 21997, 21998, 21999, 22000, 22001, 22002, 22003, 22004, 22005, 22225, 22308, 22313, 22530, 22534, 22535, 23515, 24030, 24034, 24035, 24556, 26555, 26559, 26560, 27147, 27151, 27152, 27207, 27211, 27212, 27261, 27266, 27327, 27328, 27332, 27333, 27334, 28286, 28683, 30006, 30007, 30008, 30009, 30010, 30011, 30012, 30013, 30966, 30967, 30968, 30969, 30970, 30971, 30972, 30973, 30974, 30975, 30976, 30977, 30978, 30979, 30980, 30981, 30982, 30983, 30984, 30985, 30986, 30987, 30988, 30989, 30990, 30991, 30992, 30993, 30994, 30995, 30996, 30997, 30998, 30999, 31000, 31001, 31002, 31003, 31004, 31005, 31006, 31007, 31008, 31009, 31010, 31011, 31012, 31013, 31014, 31015, 31016, 31017, 31018, 31019, 31020, 31021, 31022, 31023, 31024, 31025, 31026, 31027, 31028, 31029, 31030, 31031, 31032, 31033, 31034, 31035, 31036, 31037, 31038, 31039, 31040, 31041, 31042, 31043, 31044, 31045, 31046, 31047, 31048, 31049, 31050, 31051, 31052, 31053, 31054, 31055, 31056, 31057, 31058, 31059, 31060, 31061, 31062, 31063, 31064, 31065, 31066, 31067, 31068, 31069, 31070, 31071, 31072, 31073, 31074, 31075, 31076, 31077, 31078, 31079, 31080, 31081, 31082, 31083, 31084, 31085, 31086, 31087, 31088, 31089, 31090, 31091, 31092, 31093, 31094, 31095, 31096, 31097, 31098, 31099, 31100, 31101, 31102, 31103, 31104, 31105, 31106, 31107, 31108, 31109, 31110, 31111, 31112, 31113, 31114, 31115, 31116, 31117, 31118, 31119, 31120, 31121, 31122, 31123, 31124, 31125, 31126, 31127, 31128, 31129, 31130, 31131, 31132, 31133, 31134, 31135, 31136, 31137, 31138, 31139, 31140, 31141, 31142, 31143, 31144, 31145, 31146, 31147, 31148, 31149, 31150, 31151, 31152, 31153, 31154, 31155, 31156, 31157, 31158, 31159, 31160, 31161, 31162, 31163, 31164, 31165, 31166, 31167, 31168, 31169, 31170, 31171, 31172, 31173, 31174, 31175, 31176, 31177, 31178, 31179, 31180, 31181, 31182, 31183, 31184, 31185, 31186, 31187, 31188, 31189, 31190, 31191, 31192, 31193, 31194, 31195, 31196, 31197, 31198, 31199, 31200, 31201, 31202, 31203, 31204, 31205, 31206, 31207, 31208, 31209, 31210, 31211, 31212, 31213, 31214, 31215, 31216, 31217, 31218, 31219, 31220, 31221, 31222, 31223, 31224, 31225, 31226, 31227, 31228, 31229, 31230, 31231, 31232, 31233, 31234, 31235, 31236, 31237, 31238, 31239, 31240, 31241, 31242, 31243, 31244, 31245, 31246, 31247, 31248, 31249, 31250, 31251, 31252, 31253, 31254, 31255, 31256, 31257, 31258, 31259, 31260, 31261, 31262, 31263, 31264, 31265, 31266, 31267, 31268, 31269, 31270, 31271, 31272, 31273, 31274, 31275, 31276, 31277, 31278, 31279, 31280, 31281, 31282, 31283, 31284, 31285, 31286, 31287, 31288, 31289, 31290, 31291, 31292, 31293, 31294, 31295, 31296, 31297, 31298, 31299, 31300, 31301, 31302, 31303, 31304, 31305, 31306, 31307, 31308, 31309, 31310, 31311, 31312, 31313, 31314, 31315, 31316, 31317, 31318, 31319, 31320, 31321, 31322, 31323, 31324, 31325, 31326, 31327, 31328, 31329, 31330, 31331, 31332, 31333, 31334, 31335, 31336, 31337, 31338, 31339, 31340, 31341, 31342, 31343, 31344, 31345, 31346, 31347, 31348, 31349, 31350, 31351, 31352, 31353, 31354, 31355, 31356, 31357, 31358, 31359, 31360, 31361, 31362, 31363, 31364, 31365, 31366, 31367, 31368, 31369, 31370, 31371, 31372, 31373, 31374, 31375, 31376, 31377, 31378, 31379, 31380, 31381, 31382, 31383, 31384, 31385, 31386, 31387, 31388, 31389, 31390, 31391, 31392, 31393, 31394, 31395, 31396, 31397, 31398, 31399, 31400, 31401, 31402, 31403, 31404, 31405, 31406, 31407, 31408, 31409, 31410, 31411, 31412, 31413, 31414, 31415, 31416, 31417, 31418, 31419, 31420, 31421, 31422, 31423, 31424, 31425, 31426, 31427, 31428, 31429, 31430, 31431, 31432, 31433, 31434, 31435, 31436, 31437, 31438, 31439, 31440, 31441, 31442, 31443, 31444, 31445, 31446, 31447, 31448, 31449, 31450, 31451, 31452, 31453, 31454, 31455, 31456, 31457, 31458, 31459, 31460, 31461, 31462, 31463, 31464, 31465, 31466, 31467, 31468, 31469, 31470, 31471, 31472, 31473, 31474, 31475, 31476, 31477, 31478, 31479, 31480, 31481, 31482, 31483, 31484, 31485, 31486, 31487, 31488, 31489, 31490, 31491, 31492, 31493, 31494, 31495, 31496, 31497, 31498, 31499, 31500, 31501, 31502, 31503, 31504, 31505, 31506, 31507, 31508, 31509, 31510, 31511, 31512, 31513, 31514, 31515, 31516, 31517, 31518, 31519, 31520, 31521, 31522, 31523, 31524, 31525, 31526, 31527, 31528, 31529, 31530, 31531, 31532, 31533, 31534, 31535, 31536, 31537, 31538, 31539, 31540, 31541, 31542, 31543, 31544, 31545, 31546, 31547, 31548, 31549, 31550, 31551, 31552, 31553, 31554, 31555, 31556, 31557, 31558, 31559, 31560, 31561, 31562, 31563, 31564, 31565, 31566, 31567, 31568, 31569, 31570, 31571, 31572, 31573, 31574, 31575, 31576, 31577, 31578, 31579, 31580, 31581, 31582, 31583, 31584, 31585, 31586, 31587, 31588, 31589, 31590, 31591, 31592, 31593, 31594, 31595, 31596, 31597, 31598, 31599, 31600, 31601, 31602, 31603, 31604, 31605, 31606, 31607, 31608, 31609, 31610, 31611, 31612, 31613, 31614, 31615, 31616, 31617, 31618, 31619, 31620, 31621, 31622, 31623, 31624, 31625, 31626, 31627, 31628, 31629, 31630, 31631, 31632, 31633, 31634, 31635, 31636, 31637, 31638, 31639, 31640, 31641, 31642, 31643, 31644, 31645, 31646, 31647, 31648, 31649, 31650, 31651, 31652, 31653, 31654, 31655, 31656, 31657, 31658, 31659, 31660, 31661, 31662, 31663, 31664, 31665, 31666, 31667, 31668, 31669, 31670, 31671, 31672, 32455, 32456, 32457, 32458, 32459, 32460, 32461, 32462, 32463, 32464, 32465, 32466, 32467, 32468, 32469, 32470, 32471, 32472, 32473, 32474, 32475, 32476, 32477, 32478, 32479, 32480, 32481, 32482, 32483, 32484, 32485, 32486, 32487, 32488, 32489, 32490, 32491, 32492, 32493, 32494, 32495, 32496, 32497, 32498, 32499, 32500, 32501, 32502, 32503, 32504, 32505, 32506, 32507, 32508, 32509, 32510, 32511, 32512, 32513, 32514, 32515, 32516, 32517, 32518, 32519, 32520, 32521, 32522, 32523, 32524, 32525, 32526, 32527, 32528, 32529, 32530, 32531, 32532, 32533, 32534, 32535, 32536, 32537, 32538, 32539, 32540, 32541, 32542, 32543, 32544, 32545, 32546, 32547, 32548, 32549, 32550, 32551, 32552, 32553, 32554, 32555, 32556, 32557, 32558, 32559, 32560, 32561, 32562, 32563, 32564, 32565, 32566, 32567, 32568, 32569, 32570, 32571, 32572, 32573, 32574, 32575, 32576, 32577, 32578, 32579, 32580, 32581, 32582, 32583, 32584, 32585, 32586, 32587, 32588, 32589, 32590, 32591, 32592, 32593, 32594, 32595, 32596, 32597, 32598, 32599, 32600, 32601, 32602, 32603, 32604, 32605, 32606, 32607, 32608, 32609, 32610, 32611, 32612, 32613, 32614, 32615, 32616, 32617, 32618, 32619, 32620, 32621, 32622, 32623, 32624, 32625, 32626, 32627, 32628, 32629, 32630, 32631, 32632, 32633, 32634, 32635, 32636, 32637, 32638, 32639, 32640, 32641, 32642, 32643, 32644, 32645, 32646, 32647, 32648, 32649, 32650, 32651, 32652, 32653, 32654, 32655, 32656, 32657, 32658, 32659, 32660, 32661, 32662, 32663, 32664, 32665, 32666, 32667, 32668, 32669, 32670, 32671, 32672, 32673, 32674, 32675, 32676, 32677, 32678, 32679, 32680, 32681, 32682, 32683, 32684, 32685, 32686, 32687, 32688, 32689, 32690, 32691, 32692, 32693, 32694, 32695, 32696, 32697, 32698, 32699, 32700, 32701, 32702, 32703, 32704, 32705, 32706, 32707, 32708, 32709, 32710, 32711, 32712, 32713, 32714, 32715, 32716, 32717, 32718, 32719, 32720, 32721, 32722, 32723, 32724, 32725, 32726, 32727, 32728, 32729, 32730, 32731, 32732, 32733, 32734, 32735, 32736, 32737, 32738, 32739, 32740, 32741, 32742, 32743, 32744, 32745, 32746, 32747, 32748, 32749, 32750, 32751, 32752, 32753, 32754, 32755, 32756, 32757, 32758, 32759, 32760, 32761, 32762, 32763, 32764, 32765, 32766, 32767, 32768, 32769, 32770, 32771, 32772, 32773, 32774, 32775, 32776, 32777, 32778, 32779, 32780, 32781, 32782, 32783, 32784, 32785, 32786, 32787, 32788, 32789, 32790, 32791, 32792, 32793, 32794, 32795, 32796, 32797, 32798, 32799, 32800, 32801, 32802, 32803, 32804, 32805, 32806, 32807, 32808, 32809, 32810, 32811, 32812, 32813, 32814, 32815, 32816, 32817, 32818, 32819, 32820, 32821, 32822, 32823, 32824, 32825, 32826, 32827, 32828, 32829, 32830, 32831, 32832, 32833, 32834, 32835, 32836, 32837, 32838, 32839, 32840, 32841, 32842, 32843, 32844, 32845, 32846, 32847, 32848, 32849, 32850, 32851, 32852, 32853, 32854, 32855, 32856, 32857, 32858, 32859, 32860, 32861, 32862, 32863, 32864, 32865, 32866, 32867, 32868, 32869, 32870, 32871, 32872, 32873, 32874, 32875, 32876, 32877, 32878, 32879, 32880, 32881, 32882, 32883, 32884, 32885, 32886, 32887, 32888, 32889, 32890, 32891, 32892, 32893, 32894, 32895, 32896, 32897, 32898, 32899, 32900, 32901, 32902, 32903, 32904, 32905, 32906, 32907, 32908, 32909, 32910, 32911, 32912, 32913, 32914, 32915, 32916, 32917, 32918, 32919, 32920, 32921, 32922, 32923, 32924, 32925, 32926, 32927, 32928, 32929, 32930, 32931, 32932, 32933, 32934, 32935, 32936, 32937, 32938, 32939, 32940, 32941, 32942, 32943, 32944, 32945, 32946, 32947, 32948, 32949, 32950, 32951, 32952, 32953, 32954, 32955, 32956, 32957, 32958, 32959, 32960, 32961, 32962, 32963, 32964, 32965, 32966, 32967, 32968, 32969, 32970, 32971, 32972, 32973, 32974, 32975, 32976, 32977, 32978, 32979, 32980, 32981, 32982, 32983, 32984, 32985, 32986, 32987, 32988, 32989, 32990, 32991, 32992, 32993, 32994, 32995, 32996, 32997, 32998, 32999, 33000, 33001, 33002, 33003, 33004, 33005, 33006, 33007, 33008, 33009, 33010, 33011, 33012, 33013, 33014, 33015, 33016, 33017, 33018, 33019, 33020, 33021, 33022, 33023, 33024, 33025, 33026, 33027, 33028, 33029, 33030, 33031, 33032, 33033, 33034, 33035, 33036, 33037, 33038, 33039, 33040, 33041, 33042, 33043, 33044, 33045, 33046, 33047, 33048, 33049, 33050, 33051, 33052, 33053, 33054, 33055, 33056, 33057, 33058, 33059, 33060, 33061, 33062, 33063, 33064, 33065, 33066, 33067, 33068, 33069, 33070, 33071, 33072, 33073, 33074, 33075, 33076, 33077, 33078, 33079, 33080, 33081, 33082, 33083, 33084, 33085, 33086, 33087, 33088, 33089, 33090, 33091, 33092, 33093, 33094, 33095, 33096, 33097, 33098, 33099, 33100, 33101, 33102, 33103, 33104, 33105, 33106, 33107, 33108, 33109, 33110, 33111, 33112, 33113, 33114, 33115, 33116, 33117, 33118, 33119, 33120, 33121, 33122, 33123, 33124, 33125, 33126, 33127, 33128, 33129, 33130, 33131, 33132, 33133, 33134, 33135, 33136, 33137, 33138, 33139, 33140, 33141, 33142, 33143, 33144, 33145, 33146, 33147, 33148, 33149, 33150, 33151, 33152, 33153, 33154, 33155, 33156, 33157, 33158, 33159, 33160, 33161, 33162, 33163, 33164, 33165, 33166, 33167, 33168, 33169, 33170, 33171, 33172, 33173, 33174, 33175, 33176, 33177, 33178, 33179, 33180, 33181, 33182, 33183, 33184, 33185, 33186, 33187, 33188, 33189, 33190, 33191, 33192, 33193, 33194, 33195, 33196, 33197, 33198, 33199, 33200, 33201, 33202, 33203, 33204, 33205, 33206, 33207, 33208, 33209, 33210, 33211, 33212, 33213, 33214, 33215, 33216, 33217, 33218, 33219, 33220, 33221, 33222, 33223, 33224, 33225, 33226, 33227, 33228, 33229, 33230, 33231, 33232, 33233, 33234, 33235, 33236, 33237, 33238, 33239, 33240, 33241, 33242, 33243, 33244, 33245, 33246, 33247, 33248, 33249, 33250, 33251, 33252, 33253, 33254, 33255, 33256, 33257, 33258, 33259, 33260, 33261, 33262, 33263, 33264, 33265, 33266, 33267, 33268, 33269, 33270, 33271, 33272, 33273, 33274, 33275, 33276, 33277, 33278, 33279, 33280, 33281, 33282, 33283, 33284, 33285, 33286, 33287, 33288, 33289, 33290, 33291, 33292, 33293, 33294, 33295, 33296, 33297, 33298, 33299, 33300, 33301, 33302, 33303, 33304, 33305, 33306, 33307, 33308, 33309, 33310, 33311, 33312, 33313, 33314, 33315, 33316, 33317, 33318, 33319, 33320, 33321, 33322, 33323, 33324, 33325, 33326, 33327, 33328, 33329, 33330, 33331, 33332, 33333, 33334, 33335, 33336, 33337, 33338, 33339, 33340, 33341, 33342, 33343, 33344, 33345, 33346, 33347, 33348, 33349, 33350, 33351, 33352, 33353, 33354, 33355, 33356, 33357, 33358, 33359, 33360, 33361, 33362, 33363, 33364, 33365, 33366, 33367, 33368, 33369, 33370, 33371, 33372, 33373, 33374, 33375, 33376, 33377, 33378, 33379, 33380, 33381, 33382, 33383, 33384, 33385, 33386, 33387, 33388, 33389, 33390, 33391, 33392, 33393, 33394, 33395, 33396, 33397, 33398, 33399, 33400, 33401, 33402, 33403, 33404, 33405, 33406, 33407, 33408, 33409, 33410, 33411, 33412, 33413, 33414, 33415, 33416, 33417, 33418, 33419, 33420, 33421, 33422, 33423, 33424, 33425, 33426, 33427, 33428, 33429, 33430, 33431, 33432, 33433, 33434, 33435, 33436, 33437, 33438, 33439, 33440, 33441, 33442, 33443, 33444, 33445, 33446, 33447, 33448, 33449, 33450, 33451, 33452, 33453, 33454, 33455, 33456, 33457, 33458, 33459, 33460, 33461, 33462, 33463, 33464, 33465, 33466, 33467, 33468, 33469, 33470, 33471, 33472, 33473, 33474, 33475, 33476, 33477, 33478, 33479, 33480, 33481, 33482, 33483, 33484, 33485, 33486, 33487, 33488, 33489, 33490, 33491, 33492, 33493, 33494, 33495, 33496, 33497, 33498, 33499, 33500, 33501, 33502, 33503, 33504, 33505, 33506, 33507, 33508, 33509, 33510, 33511, 33512, 33513, 33514, 33515, 33516, 33517, 33518, 33519, 33520, 33521, 33522, 33523, 33524, 33525, 33526, 33527, 33528, 33529, 33530, 33531, 33532, 33533, 33534, 33535, 33536, 33537, 33538, 33539, 33540, 33541, 33542, 33543, 33544, 33545, 33546, 33547, 33548, 33549, 33550, 33551, 33552, 33553, 33554, 33555, 33556, 33557, 33558, 33559, 33560, 33561, 33562, 33563, 33564, 33565, 33566, 33567, 33568, 33569, 33570, 33571, 33572, 33573, 33574, 33575, 33576, 33577, 33578, 33579, 33580, 33581, 33582, 33583, 33584, 33585, 33586, 33587, 33588, 33589, 33590, 33591, 33592, 33593, 33594, 33595, 33596, 33597, 33598, 33599, 33600, 33601, 33602, 33603, 33604, 33605, 33606, 33607, 33608, 33609, 33610, 33611, 33612, 33613, 33614, 33615, 33616, 33617, 33618, 33619, 33620, 33621, 33622, 33623, 33624, 33625, 33626, 33627, 33628, 33629, 33630, 33631, 33632, 33633, 33634, 33635, 33636, 33637, 33638, 33639, 33640, 33641, 33642, 33643, 33644, 33645, 33646, 33647, 33648, 33649, 33650, 33651, 33652, 33653, 33654, 33655, 33656, 33657, 33658, 33659, 33660, 33661, 33662, 33663, 33664, 33665, 33666, 33667, 33668, 33669, 33670, 33671, 33672, 33673, 33674, 33675, 33676, 33677, 33678, 33679, 33680, 33681, 33682, 33683, 33684, 33685, 33686, 33687, 33688, 33689, 33690, 33691, 33692, 33693, 33694, 33695, 33696, 33697, 33698, 33699, 33700, 33701, 33702, 33703, 33704, 33705, 33706, 33707, 33708, 33709, 33710, 33711, 33712, 33713, 33714, 33715, 33716, 33717, 33718, 33719, 33720, 33721, 33722, 33723, 33724, 33725, 33726, 33727, 33728, 33729, 33730, 33731, 33732, 33733, 33734, 33735, 33736, 33737, 33738, 33739, 33740, 33741, 33742, 33743, 33744, 33745, 33746, 33747, 33748, 33749, 33750, 33751, 33752, 33753, 33754, 33755, 33756, 33757, 33758, 33759, 33760, 33761, 33762, 33763, 33764, 33765, 33766, 33767, 33768, 33769, 33770, 33771, 33772, 33773, 33774, 33775, 33776, 33777, 33778, 33779, 33780, 33781, 33782, 33783, 33784, 33785, 33786, 33787, 33788, 33789, 33790, 33791, 33792, 33793,

In [63]:
np.where(df1.iloc[np.array(mismatch_idx)]['bliss .dat path 1'].values.astype(str)=='nan')[0]

array([], dtype=int64)

In [67]:
df1.iloc[np.array(mismatch_idx)].iloc[1623]

Unnamed: 0                                                           32515
Unnamed: 0.1                                                         32515
Unnamed: 0.1.1                                                       32515
Target                                                            HIP83043
RA                                                             16 58 8.71
DEC                                                              25 44 30
Distance (pc)                                                         10.3
Cadence ID                                                           21089
Cadence Type                                                        ABACAD
Receiver                                                           Rcvr2_3
Vmag                                                                   9.7
Spectral Type                                                           M2
.h5 path 1               /datag/pipeline/AGBT17B_999_29/blc15/blc15_gup...
.h5 path 2               /datag/pipeline/AGBT17B_999_29/blc15/blc15_gup...
.h5 path 3               /datag/pipeline/AGBT17B_999_29/blc15/blc15_gup...
.h5 path 4               /datag/pipeline/AGBT17B_999_29/blc15/blc15_gup...
.h5 path 5               /datag/pipeline/AGBT17B_999_29/blc15/blc15_gup...
.h5 path 6               /datag/pipeline/AGBT17B_999_29/blc15/blc15_gup...
turboSETI .dat path 1    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 2    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 3    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 4    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 5    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 6    /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 1              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 2              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 3              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 4              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 5              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 6              /datax/scratch/benjb/bl_nearby_stars/seticore_...
bliss .dat path 1        /datax/scratch/benjb/bl_nearby_stars/all_bliss...
bliss .dat path 2                                                      NaN
bliss .dat path 3                                                      NaN
bliss .dat path 4                                                      NaN
bliss .dat path 5                                                      NaN
bliss .dat path 6                                                      NaN
turboSETI event .csv                                                   NaN
Name: 32515, dtype: object

In [69]:
print(df1.iloc[32515]['bliss .dat path 1'])

/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/32515_1_blc15_guppi_58008_00330_HIP83043_0031.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat

In [ ]:
1623, dat path 2, 3, 4, 5, 6
58, dat path 4

In [45]:
fff = glob.glob('/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/*.dat')
print(len(fff))

22722

In [40]:
df.iloc[4355]

Target                                                           HIP111169
RA                                                             22 31 17.7
DEC                                                              50 16 57
Distance (pc)                                                         31.3
Cadence ID                                                          421076
Cadence Type                                                        ABACAD
Receiver                                                      Rcvr8_10_NEW
Vmag                                                                  3.76
Spectral Type                                                          A1V
.h5 path 1               /datag/pipeline/AGBT23B_999_08/blc25_blp25/blc...
.h5 path 2               /datag/pipeline/AGBT23B_999_08/blc25_blp25/blc...
.h5 path 3               /datag/pipeline/AGBT23B_999_08/blc25_blp25/blc...
.h5 path 4               /datag/pipeline/AGBT23B_999_08/blc25_blp25/blc...
.h5 path 5               /datag/pipeline/AGBT23B_999_08/blc25_blp25/blc...
.h5 path 6               /datag/pipeline/AGBT23B_999_08/blc25_blp25/blc...
turboSETI .dat path 1    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 2    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 3    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 4                                                 None
turboSETI .dat path 5    /datax/scratch/benjb/bl_nearby_stars/seticore_...
turboSETI .dat path 6    /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 1              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 2              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 3              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 4                                                           None
.dat path 5              /datax/scratch/benjb/bl_nearby_stars/seticore_...
.dat path 6              /datax/scratch/benjb/bl_nearby_stars/seticore_...
bliss .dat path 1        /datax/scratch/benjb/bl_nearby_stars/respliced...
bliss .dat path 2        /datax/scratch/benjb/bl_nearby_stars/respliced...
bliss .dat path 3        /datax/scratch/benjb/bl_nearby_stars/respliced...
bliss .dat path 4        /datax/scratch/benjb/bl_nearby_stars/respliced...
bliss .dat path 5        /datax/scratch/benjb/bl_nearby_stars/respliced...
bliss .dat path 6        /datax/scratch/benjb/bl_nearby_stars/respliced...
turboSETI event .csv                                                   NaN
Name: 4355, dtype: object

In [39]:
i = 4355
print(df['.h5 path 1'].values[i])
print(df['.h5 path 2'].values[i])
print(df['.h5 path 3'].values[i])
print(df['.h5 path 4'].values[i])
print(df['.h5 path 5'].values[i])
print(df['.h5 path 6'].values[i])
print(df['turboSETI .dat path 1'].values[i])
print(df['turboSETI .dat path 2'].values[i])
print(df['turboSETI .dat path 3'].values[i])
print(df['turboSETI .dat path 4'].values[i])
print(df['turboSETI .dat path 5'].values[i])
print(df['turboSETI .dat path 6'].values[i])
print(df['bliss .dat path 1'].values[i])
print(df['bliss .dat path 2'].values[i])
print(df['bliss .dat path 3'].values[i])
print(df['bliss .dat path 4'].values[i])
print(df['bliss .dat path 5'].values[i])
print(df['bliss .dat path 6'].values[i])

/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_21482_HIP111147_0062.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_21798_HIP111169_0063.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_22127_HIP111868_0064.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_22453_HIP111169_0065.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_22769_HIP111178_0066.rawspec.0000.h5
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_21171_HIP111169_0061.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_21482_HIP111147_0062.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_21798_HIP111169_0063.rawspec.0000.dat
None
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_22453_HIP111169_0065.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_22769_HIP111178_0066.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4355_1_0_blc61_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4355_2_0_blc61_guppi_58475_01773_HIP112173_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4355_3_0_blc61_guppi_58475_02119_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4355_4_0_blc62_guppi_58475_02457_HIP112360_0017.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4355_5_0_blc61_guppi_58475_02795_HIP112909_0018.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/4355_6_0_blc61_guppi_58475_03129_HIP112422_0019.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat

In [78]:
for f in df.iloc[np.where(df['Target'].values=='HIP112909')[0]]['bliss .dat path 1'].values:
    print(f)

/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4861_1_0_spliced_blc0001020304050607_guppi_57530_44340_HIP112909_0003.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4862_1_0_spliced_blc0001020304050607_guppi_57760_81365_HIP112909_0003.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4863_1_blc00_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4864_1_blc01_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4865_1_blc02_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4866_1_blc03_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4867_1_blc04_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4868_1_blc05_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4869_1_blc06_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4870_1_blc10_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4871_1_blc07_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4872_1_blc11_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4873_1_blc12_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4874_1_blc13_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4875_1_blc14_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4876_1_blc15_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4877_1_blc16_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4878_1_blc20_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4879_1_blc17_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4880_1_blc21_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4881_1_blc22_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4882_1_blc23_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4883_1_blc24_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4884_1_blc25_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4885_1_blc26_guppi_58340_33822_HIP112909_0016.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4886_1_blc00_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4887_1_blc01_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4888_1_blc02_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4889_1_blc03_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4890_1_blc04_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4891_1_blc05_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4892_1_blc06_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4893_1_blc10_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4894_1_blc07_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4895_1_blc11_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4896_1_blc12_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4897_1_blc13_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4898_1_blc14_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4899_1_blc15_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4900_1_blc16_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4901_1_blc20_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4902_1_blc17_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4903_1_blc21_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4904_1_blc22_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4905_1_blc23_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4906_1_blc24_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4907_1_blc25_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4908_1_blc26_guppi_58354_29018_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4909_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58403_16439_HIP112909_0104.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4910_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58414_07191_HIP112909_0111.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4911_1_blc30_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4912_1_blc31_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4913_1_blc32_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4914_1_blc33_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4915_1_blc34_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4916_1_blc35_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4917_1_blc36_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4918_1_blc40_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4919_1_blc37_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4920_1_blc41_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4921_1_blc42_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4922_1_blc43_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4923_1_blc44_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4924_1_blc45_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4925_1_blc46_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4926_1_blc50_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4927_1_blc47_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4928_1_blc51_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4929_1_blc52_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4930_1_blc53_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4931_1_blc54_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4932_1_blc55_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4933_1_blc56_guppi_58416_06216_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4934_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58417_14413_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4935_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58428_06721_HIP112909_0082.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4936_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58429_12397_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4937_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58437_10439_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4938_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58445_83098_HIP112909_0106.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_dats_from_blpc0/4939_1_0_spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58450_06490_HIP112909_0015.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4940_1_blc40_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4941_1_blc41_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4942_1_blc42_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4943_1_blc43_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4944_1_blc44_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4945_1_blc45_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4946_1_blc46_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4947_1_blc50_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4948_1_blc47_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4949_1_blc51_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4950_1_blc52_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4951_1_blc53_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4952_1_blc54_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4953_1_blc55_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4954_1_blc56_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4955_1_blc60_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4956_1_blc57_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4957_1_blc61_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4958_1_blc62_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4959_1_blc63_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4960_1_blc64_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4961_1_blc65_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4962_1_blc66_guppi_58469_84882_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4963_1_blc40_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4964_1_blc41_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4965_1_blc42_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4966_1_blc43_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4967_1_blc44_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4968_1_blc45_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4969_1_blc46_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4970_1_blc50_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4971_1_blc47_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4972_1_blc51_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4973_1_blc52_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4974_1_blc53_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4975_1_blc54_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4976_1_blc55_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4977_1_blc56_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4978_1_blc60_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4979_1_blc57_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4980_1_blc61_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4981_1_blc62_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4982_1_blc63_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4983_1_blc64_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4984_1_blc65_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4985_1_blc66_guppi_58475_01427_HIP112909_0014.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat

In [48]:
i = 4355
print(df1['.h5 path 1'].values[i])
print(df1['.h5 path 2'].values[i])
print(df1['.h5 path 3'].values[i])
print(df1['.h5 path 4'].values[i])
print(df1['.h5 path 5'].values[i])
print(df1['.h5 path 6'].values[i])
print(df1['turboSETI .dat path 1'].values[i])
print(df1['turboSETI .dat path 2'].values[i])
print(df1['turboSETI .dat path 3'].values[i])
print(df1['turboSETI .dat path 4'].values[i])
print(df1['turboSETI .dat path 5'].values[i])
print(df1['turboSETI .dat path 6'].values[i])
print(df1['bliss .dat path 1'].values[i])
print(df1['bliss .dat path 2'].values[i])
print(df1['bliss .dat path 3'].values[i])
print(df1['bliss .dat path 4'].values[i])
print(df1['bliss .dat path 5'].values[i])
print(df1['bliss .dat path 6'].values[i])

/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_21171_HIP111169_0061.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_21482_HIP111147_0062.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_21798_HIP111169_0063.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_22127_HIP111868_0064.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_22453_HIP111169_0065.rawspec.0000.h5
/datag/pipeline/AGBT23B_999_08/blc25_blp25/blc25_guppi_60277_22769_HIP111178_0066.rawspec.0000.h5
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_21171_HIP111169_0061.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_21482_HIP111147_0062.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_21798_HIP111169_0063.rawspec.0000.dat
None
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_22453_HIP111169_0065.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc25_guppi_60277_22769_HIP111178_0066.rawspec.0000.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4355_1_blc25_guppi_60277_21171_HIP111169_0061.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4355_2_blc25_guppi_60277_21482_HIP111147_0062.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4355_3_blc25_guppi_60277_21798_HIP111169_0063.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
nan
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4355_5_blc25_guppi_60277_22453_HIP111169_0065.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/all_bliss_dats_060226/4355_6_blc25_guppi_60277_22769_HIP111178_0066.rawspec.0000_nosig_nosk_SNR_20_L1_30.dat

In [75]:
fffbad = np.sort(glob.glob('/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/*.dat'))
for f in fffbad:
    if 'HIP1111' in f:
        print(f)

/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32720_6_0_blc40_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32721_6_0_blc41_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32722_6_0_blc42_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32723_6_0_blc43_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32724_6_0_blc44_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32725_6_0_blc45_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32726_6_0_blc46_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32727_6_0_blc50_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32728_6_0_blc47_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32729_6_0_blc51_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32730_6_0_blc52_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32731_6_0_blc53_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32732_6_0_blc54_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32733_6_0_blc55_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32734_6_0_blc56_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32735_6_0_blc60_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32736_6_0_blc57_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32737_6_0_blc61_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32738_6_0_blc62_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32739_6_0_blc63_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32740_6_0_blc64_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32741_6_0_blc65_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat
/datax/scratch/benjb/bl_nearby_stars/respliced_unspliced_dats/32742_6_0_blc66_guppi_58520_06606_HIP11111_0063.gpuspec.0000_nosig_nosk_SNR_20_L1_30.dat

In [70]:
with open(df1.iloc[32515]['bliss .dat path 1'], mode='r') as f:
    lines = f.readlines()
    for l in lines:
        print(l)

In [7]:
print(s4)
print(s5)
print(s6)

['/datag/pipeline/AGBT23B_999_23/blc11_blp11/blc11_guppi_60306_38062_HIP38674_0118.rawspec.0000.h5']
['/datag/pipeline/AGBT23B_999_23/blc11_blp11/blc11_guppi_60306_38380_HIP38625_0119.rawspec.0000.h5']
['/datag/pipeline/AGBT18A_999_48/holding/spliced_blc00010203040506o7o0111213141516o7o0212223242526o7o031323334353637_guppi_58231_58600_HIP113384_0037.gpuspec.0000.h5']

In [ ]:
'''symlink_dir = '/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/turboSETI_hdf5_symlinks'

# create symlinks for all hdf5 files and add them to CSV

sl1 = []
sl2 = []
sl3 = []
sl4 = []
sl5 = []
sl6 = []

for i in range(len(df)):
    h5_1 = df['.h5 path 1'].values[i]
    h5_2 = df['.h5 path 2'].values[i]
    h5_3 = df['.h5 path 3'].values[i]
    h5_4 = df['.h5 path 4'].values[i]
    h5_5 = df['.h5 path 5'].values[i]
    h5_6 = df['.h5 path 6'].values[i]
    dat_1 = df['turboSETI .dat path 1'].values[i]
    dat_2 = df['turboSETI .dat path 2'].values[i]
    dat_3 = df['turboSETI .dat path 3'].values[i]
    dat_4 = df['turboSETI .dat path 4'].values[i]
    dat_5 = df['turboSETI .dat path 5'].values[i]
    dat_6 = df['turboSETI .dat path 6'].values[i]
    turboSETI_symlink_1 = f'{symlink_dir}/{os.path.basename(dat_1)[:-3]}h5'
    turboSETI_symlink_2 = f'{symlink_dir}/{os.path.basename(dat_2)[:-3]}h5'
    turboSETI_symlink_3 = f'{symlink_dir}/{os.path.basename(dat_3)[:-3]}h5'
    turboSETI_symlink_4 = f'{symlink_dir}/{os.path.basename(dat_4)[:-3]}h5'
    turboSETI_symlink_5 = f'{symlink_dir}/{os.path.basename(dat_5)[:-3]}h5'
    turboSETI_symlink_6 = f'{symlink_dir}/{os.path.basename(dat_6)[:-3]}h5'
    sl1.append(turboSETI_symlink_1)
    sl2.append(turboSETI_symlink_2)
    sl3.append(turboSETI_symlink_3)
    sl4.append(turboSETI_symlink_4)
    sl5.append(turboSETI_symlink_5)
    sl6.append(turboSETI_symlink_6)
    console = f'ln -s {h5_1} {turboSETI_symlink_1}'
    os.system(console)
    console = f'ln -s {h5_2} {turboSETI_symlink_2}'
    os.system(console)
    console = f'ln -s {h5_3} {turboSETI_symlink_3}'
    os.system(console)
    console = f'ln -s {h5_4} {turboSETI_symlink_4}'
    os.system(console)
    console = f'ln -s {h5_5} {turboSETI_symlink_5}'
    os.system(console)
    console = f'ln -s {h5_6} {turboSETI_symlink_6}'
    os.system(console)
    # if i == 6612:
    #     print(dat_1)
    #     print(turboSETI_symlink_1)
    #     break

df.insert(16, 'turboSETI .h5 symlink 6', sl6)
df.insert(16, 'turboSETI .h5 symlink 5', sl5)
df.insert(16, 'turboSETI .h5 symlink 4', sl4)
df.insert(16, 'turboSETI .h5 symlink 3', sl3)
df.insert(16, 'turboSETI .h5 symlink 2', sl2)
df.insert(16, 'turboSETI .h5 symlink 1', sl1)

df.keys()

# go through all .dat files, create symlinks to the corresponding .hdf5 files, and add the symlinks as 6 new columns'''

Index(['Unnamed: 0', 'Target', 'RA', 'DEC', 'Distance (pc)', 'Cadence ID',
       'Cadence Type', 'Receiver', 'Vmag', 'Spectral Type', '.h5 path 1',
       '.h5 path 2', '.h5 path 3', '.h5 path 4', '.h5 path 5', '.h5 path 6',
       'turboSETI .h5 symlink 1', 'turboSETI .h5 symlink 2',
       'turboSETI .h5 symlink 3', 'turboSETI .h5 symlink 4',
       'turboSETI .h5 symlink 5', 'turboSETI .h5 symlink 6',
       'turboSETI .dat path 1', 'turboSETI .dat path 2',
       'turboSETI .dat path 3', 'turboSETI .dat path 4',
       'turboSETI .dat path 5', 'turboSETI .dat path 6', '.dat path 1',
       '.dat path 2', '.dat path 3', '.dat path 4', '.dat path 5',
       '.dat path 6'],
      dtype='object')

In [ ]:
# dfh = df.iloc[np.where((df['Target'].values == 'HIP4849') & (df['Receiver'].values == 'Rcvr8_10'))[0]]
# for i, h5 in enumerate(dfh['.h5 path 1']):
#     print(dfh['Cadence ID'].values[i], h5)

30515 /datag/pipeline/AGBT18B_999_09/blc40/blc00_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc41/blc01_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc42/blc02_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc43/blc03_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc44/blc04_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc45/blc05_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc46/blc06_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc50/blc10_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc47/blc07_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc51/blc11_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc52/blc12_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc53/blc13_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc54/blc14_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc55/blc15_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc56/blc16_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc60/blc20_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc57/blc17_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc61/blc21_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc62/blc22_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc63/blc23_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc64/blc24_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc65/blc25_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
30515 /datag/pipeline/AGBT18B_999_09/blc66/blc26_guppi_58354_45517_HIP4849_0063.gpuspec.0000.h5
33164 /datag/pipeline/AGBT18B_999_48/collate1/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58417_30809_HIP4849_0063.gpuspec.0000.h5
33773 /datag/pipeline/AGBT18B_999_55/holding/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58429_28764_HIP4849_0063.gpuspec.0000.h5
34376 /datag/pipeline/AGBT18B_999_65/holding/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58440_26177_HIP4849_0063.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp00/blc40_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp01/blc41_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp02/blc42_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp03/blc43_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp04/blc44_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp05/blc45_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp06/blc46_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp10/blc50_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp07/blc47_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp11/blc51_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp12/blc52_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp13/blc53_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp14/blc54_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp15/blc55_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp16/blc56_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp20/blc60_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp17/blc57_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp21/blc61_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp22/blc62_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp23/blc63_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp24/blc64_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp25/blc65_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35127 /datag/pipeline/AGBT18B_999_74/blp26/blc66_guppi_58456_14166_HIP4849_0107.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp00/blc40_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp01/blc41_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp02/blc42_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp03/blc43_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp04/blc44_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp05/blc45_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp06/blc46_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp10/blc50_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp07/blc47_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp11/blc51_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp12/blc52_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp13/blc53_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp14/blc54_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp15/blc55_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp16/blc56_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp20/blc60_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp17/blc57_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp21/blc61_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp22/blc62_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp23/blc63_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp24/blc64_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp25/blc65_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35568 /datag/pipeline/AGBT18B_999_83/blp26/blc66_guppi_58470_14997_HIP4849_0062.gpuspec.0000.h5
35904 /datag/pipeline/AGBT18B_999_87/holding/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58481_08170_HIP4849_0035.gpuspec.0000.h5
36216 /datag/pipeline/AGBT18B_999_90/collate2/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58486_06278_HIP4849_0100.gpuspec.0000.h5
36422 /datag/pipeline/AGBT18B_999_92/collate1/spliced_blc00010203040506o7o0111213141516o7o021222324252627_guppi_58493_14747_HIP4849_0068.gpuspec.0000.h5

In [ ]:
# df.iloc[np.where(df['Cadence Type'].values == 'ABABAB')[0]]

,Target,RA,DEC,Distance (pc),Cadence ID,Cadence Type,Receiver,Vmag,Spectral Type,.h5 path 1,...,.h5 path 3,.h5 path 4,.h5 path 5,.h5 path 6,.dat path 1,.dat path 2,.dat path 3,.dat path 4,.dat path 5,.dat path 6
11950,HIP25110,5 22 33.0,79 13 54,20.9,29635,ABABAB,Rcvr8_10,5.08,F6V,/datag/pipeline/AGBT18A_999_92/collate/spliced...,...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datag/pipeline/AGBT18A_999_92/collate/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11951,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datag/pipeline/AGBT18B_999_67/blp00/blc30_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11952,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datag/pipeline/AGBT18B_999_67/blp01/blc31_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11953,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datag/pipeline/AGBT18B_999_67/blp02/blc32_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
11954,HIP25110,5 22 33.0,79 13 54,20.9,34576,ABABAB,Rcvr4_6,5.08,F6V,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datag/pipeline/AGBT18B_999_67/blp03/blc33_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36599,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datag/pipeline/AGBT18B_999_08/blp22/blc22_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36600,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datag/pipeline/AGBT18B_999_08/blp23/blc23_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36601,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datag/pipeline/AGBT18B_999_08/blp24/blc24_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36602,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datag/pipeline/AGBT18B_999_08/blp25/blc25_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
36603,HIP94083,19 9 10.1,76 33 35,27.2,30448,ABABAB,Rcvr8_10,5.11,A9V,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datag/pipeline/AGBT18B_999_08/blp26/blc26_gup...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...

In [ ]:
# df.iloc[np.where(df['Cadence Type'].values == 'None')[0]]

,Target,RA,DEC,Distance (pc),Cadence ID,Cadence Type,Receiver,Vmag,Spectral Type,.h5 path 1,...,.h5 path 3,.h5 path 4,.h5 path 5,.h5 path 6,.dat path 1,.dat path 2,.dat path 3,.dat path 4,.dat path 5,.dat path 6
204,GJ166,4 15 13.8,-7 40 4,4.98,6646,None,Rcvr1_2,4.43,K0.5V,/datag/pipeline/AGBT16A_999_77/holding/spliced...,...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datag/pipeline/AGBT16A_999_77/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
363,GJ280,7 39 17.3,5 13 13,3.50,6380,None,Rcvr1_2,0.37,F5IV,/datag/pipeline/AGBT16A_999_66/holding/spliced...,...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datag/pipeline/AGBT16A_999_66/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
401,GJ388,10 19 35.8,19 52 9,4.88,1132,None,Rcvr1_2,9.29,M2.5V,/datag/pipeline/AGBT16A_999_140/collate/splice...,...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datag/pipeline/AGBT16A_999_140/collate/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
402,GJ388,10 19 35.8,19 52 9,4.88,1543,None,Rcvr1_2,9.29,M2.5V,/datag/pipeline/AGBT16A_999_154/holding/splice...,...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
404,GJ388,10 19 35.8,19 52 9,4.88,1549,None,Rcvr1_2,9.29,M2.5V,/datag/pipeline/AGBT16A_999_154/holding/splice...,...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datag/pipeline/AGBT16A_999_154/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38498,HIP9884,2 7 10.6,23 27 42,20.20,1007,None,Rcvr1_2,2.01,K2III,/datag/pipeline/AGBT16A_999_136/holding/splice...,...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
38500,HIP9884,2 7 10.6,23 27 42,20.20,1013,None,Rcvr1_2,2.01,K2III,/datag/pipeline/AGBT16A_999_136/holding/splice...,...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datag/pipeline/AGBT16A_999_136/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
38528,HIP98906,20 5 0.05,54 25 48,15.80,6090,None,Rcvr2_3,11.90,M3,/datag/pipeline/AGBT16A_999_53/holding/spliced...,...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datag/pipeline/AGBT16A_999_53/holding/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
38614,HIP99031,20 6 21.4,35 58 13,24.10,6823,None,Rcvr1_2,5.38,K0IV,/datag/pipeline/AGBT16A_999_83/holding/spliced...,...,/datag/pipeline/AGBT16A_999_83/holding/spliced...,/datag/pipeline/AGBT16A_999_83/holding/spliced...,/datag/pipeline/AGBT16A_999_83/holding/spliced...,/datag/pipeline/AGBT16A_999_83/collate/spliced...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...
39079,LHS292,10 48 13.2,-11 20 38,4.53,1613,None,Rcvr1_2,15.70,M6.5V,/datag/pipeline/AGBT16A_999_157/holding/splice...,...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datag/pipeline/AGBT16A_999_157/holding/splice...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...,/datax/scratch/benjb/bl_nearby_stars/seticore_...

In [ ]:
'''full_target_list = df['Target'].values
full_cadence_id_list = df['Cadence ID'].values
full_receiver_list = df['Receiver'].values
for i in range(len(full_target_list)):
    cadences = full_cadence_id_list[i:i+1]
    receivers = np.unique(full_receiver_list[i:i+1])
    targets = []
    for j in range(6):
        t = df['.h5 path 1'].values[i+j].split('guppi_')[1][12:-21]
        if len(t) < 3:
            t = df['.h5 path 1'].values[i+j].split('guppi_')[1][6:-21] # account for GJ15B cadence listed with only integer MJD
        targets.append(t.upper()) # some stars not recorded in all uppercase

    odd_targets = np.unique(targets[::2])
    even_targets = np.unique(targets[1::2])
    cadence_type = 'None'
    for t in odd_targets:
        if 'OFF' in t:
            if len(even_targets) == 1:
                cadence_type = 'BACADA'
    for t in even_targets:
        if 'OFF' in t:
            if len(odd_targets) == 1:
                cadence_type = 'ABACAD'
    if cadence_type == 'None':
        n_odd_ons = len(np.unique(targets[::2]))
        n_even_ons = len(np.unique(targets[1::2]))
        if (n_odd_ons == 1) & (n_even_ons == 1):
            cadence_type = 'ABABAB'
        if (n_odd_ons == 1) & (n_even_ons != 1):
            cadence_type = 'ABACAD'
        if (n_odd_ons != 1) & (n_even_ons == 1):
            cadence_type = 'BACADA'
    if cadence_type == 'ABABAB':
        print(cadence_type, receivers, targets)
    
    # print(cadences)
    # print(targets)
    if i > 10:
        break
'''

In [ ]:
print(np.unique(df['Receiver'].values))

In [ ]:
### The full run on all data must include the following:

### - check for ABACAD vs BACADA

### - check that all 'ON' pointings are the same target even if not named exactly the same
### ----- e.g. GJ1245AC vs GJ1245B
### THIS IS OKAY — IF NAMED SEPARATELY, THEY ARE FAR ENOUGH APART NOT TO BE SEARCHED SIMULTANEOUSLY

### - check for band and only retain hits from proper sensitivity range
### ----- this will be hard for X-band, where the new receiver requires checking for number of banks

### DONE WITH THE ABOVE
### Now need to implement this with multiprocessing.

In [ ]:
full_target_list = df['Target'].values
full_cadence_id_list = df['Cadence ID'].values
code = 'turboSETI'
full_h5_list_1 = df[f'{code} .h5 symlink 1'].values
full_h5_list_2 = df[f'{code} .h5 symlink 2'].values
full_h5_list_3 = df[f'{code} .h5 symlink 3'].values
full_h5_list_4 = df[f'{code} .h5 symlink 4'].values
full_h5_list_5 = df[f'{code} .h5 symlink 5'].values
full_h5_list_6 = df[f'{code} .h5 symlink 6'].values
full_dat_list_1 = df[f'{code} .dat path 1'].values
full_dat_list_2 = df[f'{code} .dat path 2'].values
full_dat_list_3 = df[f'{code} .dat path 3'].values
full_dat_list_4 = df[f'{code} .dat path 4'].values
full_dat_list_5 = df[f'{code} .dat path 5'].values
full_dat_list_6 = df[f'{code} .dat path 6'].values
full_receiver_list = df['Receiver'].values

data_loc = '/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent'

start_counter = 0

In [14]:
ff = glob.glob('/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/*HIP117463*trimmed.csv')
for f in ff:
    print(f)

/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6927_31458_HIP117463_Rcvr4_6_blc55_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6926_31458_HIP117463_Rcvr4_6_blc54_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6950_31458_HIP117463_Rcvr4_6_blc54_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6951_31458_HIP117463_Rcvr4_6_blc55_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6952_33338_HIP117463_Rcvr4_6_splic_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6953_35491_HIP117463_Rcvr4_6_splic_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6980_43410_HIP117463_Rcvr4_6_blc74_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6981_43410_HIP117463_Rcvr4_6_blc75_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6982_43410_HIP117463_Rcvr4_6_blc76_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/7012_419538_HIP117463_Rcvr1_2_blc45_f3_trimmed.csv
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/7010_419538_HIP117463_Rcvr1_2_blc43_f3_trimmed.csv

In [15]:
print('/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc54_guppi_58369_31692_HIP117463_0027.gpuspec.0000.dat')

/datax/scratch/benjb/bl_nearby_stars/seticore_output/beyond_5.1_pc_accelerated/blc54_guppi_58369_31692_HIP117463_0027.gpuspec.0000.dat

In [5]:
index_for_reassignment = []
ambfiles = glob.glob('/datax/scratch/benjb/bl_nearby_stars/seticore_output/dats_for_basename_ambiguity/*.dat')
for f in ambfiles:
    idx = os.path.basename(f).split('_')[0]
    index_for_reassignment.append(int(idx))
index_for_reassignment = np.unique(index_for_reassignment)
print(index_for_reassignment)
print(len(index_for_reassignment))

[ 6612  6613  6614  6615  6616  6635  6637  6638  6639  6640  6710  6711
  6712  6713  6714  6733  6735  6736  6737  6738  6796  6797  6798  6799
  6800  6819  6821  6822  6823  6824  6923  6924  6925  6926  6927  6946
  6948  6949  6950  6951  7014  7015  7016  7017  7018  7037  7039  7040
  7041  7042  9690  9691  9692  9693  9694  9713  9715  9716  9717  9718
  9751  9752  9753  9754  9755  9774  9776  9777  9778  9779  9813  9814
  9815  9816  9817  9836  9838  9839  9840  9841  9898  9899  9900  9901
  9902  9921  9923  9924  9925  9926  9945  9946  9947  9948  9949  9968
  9970  9971  9972  9973 15940 15941 15942 15943 15944 15963 15965 15966
 15967 15968 16058 16059 16060 16061 16062 16081 16083 16084 16085 16086
 16196 16197 16198 16199 16200 16219 16221 16222 16223 16224 16396 16397
 16417 16419 16549 16550 16571 16573]
138

In [16]:
print('/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/9690_31472_HIP19855_Rcvr4_6_blc51_dat_files.lst')

/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/9690_31472_HIP19855_Rcvr4_6_blc51_dat_files.lst

In [17]:
print('/datax/scratch/benjb/bl_nearby_stars/seticore_output/dats_for_basename_ambiguity/9690_blc51_guppi_58369_38714_HIP19313_0046.gpuspec.0000.dat')

/datax/scratch/benjb/bl_nearby_stars/seticore_output/dats_for_basename_ambiguity/9690_blc51_guppi_58369_38714_HIP19313_0046.gpuspec.0000.dat

In [ ]:
print('/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6612_31440_HIP116971_Rcvr4_6_blc51_h5_files.lst')
print('/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6612_31440_HIP116971_Rcvr4_6_blc51_dat_files.lst')

# Notes
# -----
# The HDF5 file is ASSUMED(!!) to have the same name as .dat files.

/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6612_31440_HIP116971_Rcvr4_6_blc51_h5_files.lst
/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/6612_31440_HIP116971_Rcvr4_6_blc51_dat_files.lst

In [ ]:
logger = logging.getLogger(__name__)

def process_files(xxx):
    n = int(xxx[0])
    bs = len(df)//31 # batch size
    bs = 0
    df0 = xxx[1]
    #cutoff = reached_here_list[int(n)]
    code = 'turboSETI'
    batch_h5_list_1 = df0[f'{code} .h5 symlink 1'].values
    batch_h5_list_2 = df0[f'{code} .h5 symlink 2'].values
    batch_h5_list_3 = df0[f'{code} .h5 symlink 3'].values
    batch_h5_list_4 = df0[f'{code} .h5 symlink 4'].values
    batch_h5_list_5 = df0[f'{code} .h5 symlink 5'].values
    batch_h5_list_6 = df0[f'{code} .h5 symlink 6'].values
    batch_dat_list_1 = df0[f'{code} .dat path 1'].values
    batch_dat_list_2 = df0[f'{code} .dat path 2'].values
    batch_dat_list_3 = df0[f'{code} .dat path 3'].values
    batch_dat_list_4 = df0[f'{code} .dat path 4'].values
    batch_dat_list_5 = df0[f'{code} .dat path 5'].values
    batch_dat_list_6 = df0[f'{code} .dat path 6'].values
    cadence_id_list = df0['Cadence ID'].values
    target_list = df0['Target'].values
    receiver_list = df0['Receiver'].values
    # Remove all handlers associated with the root logger object.
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)
    logging.basicConfig(filename=f'{data_loc}/002_{n}_100125.log', filemode="a", level=logging.DEBUG)


    for i in range(len(batch_h5_list_1)):

        if not n*bs+i in index_for_reassignment:
            #logger.info('Already searched correctly.')
            continue

        logger.info(f'Searching #{i+1} of {len(batch_h5_list_1)} files ...')

        #if i+1 < cutoff:
        #    print('Already searched this file; continuing ...')
        #    continue

        # for each set of 6 files, run FindEvent and PlotEvent

        h5_list = np.array([
            batch_h5_list_1[i],
            batch_h5_list_2[i],
            batch_h5_list_3[i],
            batch_h5_list_4[i],
            batch_h5_list_5[i],
            batch_h5_list_6[i],
            ])
        dat_list = np.array([
            batch_dat_list_1[i],
            batch_dat_list_2[i],
            batch_dat_list_3[i],
            batch_dat_list_4[i],
            batch_dat_list_5[i],
            batch_dat_list_6[i],
            ])

        # check that all h5 files in cadence exist and were searched
        # (not true for 3 files, 5 occurrences)
        if 'None' in dat_list:
            continue

        target = target_list[i]
        cadence_id = cadence_id_list[i]
        receiver = receiver_list[i]
        s = dat_list[0].split('blc')
        if ('spliced' in dat_list[0]) & (s[1][2] == '_'):
            node = 'blc'+s[1][:2]
        else:
            node = 'blc'+os.path.basename(batch_h5_list_1[i]).split('blc')[1][:2]

        # This block checks the cadence type:
        # Either ABACAD, BACADA, or None (if not a real cadence).
        # ABABAB is also checked, but does not occur in this dataset.
        #cadences = full_cadence_id_list[6*i:6*i+6]
        #receivers = np.unique(full_receiver_list[6*i:6*i+6])
        targets = []
        for j in range(6):
            t = h5_list[j].split('guppi_')[1][12:-21]
            if len(t) < 3:
                t = h5_list.split('guppi_')[1][6:-21] # account for GJ15B cadence listed with only integer MJD
            targets.append(t.upper()) # some stars not recorded in all uppercase
        odd_targets = np.unique(targets[::2])
        even_targets = np.unique(targets[1::2])
        cadence_type = 'None'
        off_check = 0
        for t in odd_targets:
            if 'OFF' in t:
                if len(even_targets) == 1:
                    cadence_type = 'BACADA'
                off_check += 1
        for t in even_targets:
            if 'OFF' in t:
                if len(odd_targets) == 1:
                    cadence_type = 'ABACAD'
                off_check += 1
        if (cadence_type == 'None') & (off_check == 0):
            n_odd_ons = len(np.unique(targets[::2]))
            n_even_ons = len(np.unique(targets[1::2]))
            if (n_odd_ons == 1) & (n_even_ons == 1):
                cadence_type = 'ABABAB'
            if (n_odd_ons == 1) & (n_even_ons != 1):
                cadence_type = 'ABACAD'
            if (n_odd_ons != 1) & (n_even_ons == 1):
                cadence_type = 'BACADA'

        #if not cadence_id == 4051:
        #    continue
        if cadence_type == 'ABACAD':
            target = targets[0]
        elif cadence_type == 'BACADA':
            target = targets[1]

        logger.info(f'{cadence_id} {cadence_type} {target} {receiver} {targets}')

        # if cadence_type == 'ABACAD':
        #     continue
        # if cadence_type == 'BACADA':
        #     continue
        if cadence_type == 'None':
            continue

        print(node)
        print(dat_list[0])

        # if (target == 'GJ412B') & (node == 'blc04') & (receiver == 'Rcvr1_2'):
        #     start_counter += 1
        
        # if start_counter == 0:
        #     continue


        on_or_off = 'None'

        if cadence_type == 'ABACAD':
            on_or_off = ['ON']
        elif cadence_type == 'BACADA':
            on_or_off = ['OFF']
        elif cadence_type == 'ABABAB':
            on_or_off = ['ON', 'OFF']

        for k, ooo in enumerate(on_or_off):
            
            if ooo == 'ON':
                target = targets[0]
            elif ooo == 'OFF':
                target = targets[1]

            csvf_path = f'{data_loc}/{n*bs+i}_{cadence_id}_{target}_{receiver}_{node}_found_event_table_3.csv'

            h5_list_path = os.path.join(data_loc, f'{n*bs+i}_{cadence_id}_{target}_{receiver}_{node}_h5_files.lst')
            logger.info(h5_list_path)
            with open(h5_list_path, 'w') as f:
                for h5_path in h5_list:
                    logger.info(h5_path)
                    f.write(h5_path + '\n')

            dat_list_path = os.path.join(data_loc, f'{n*bs+i}_{cadence_id}_{target}_{receiver}_{node}_dat_files.lst')
            logger.info(dat_list_path)
            with open(dat_list_path, 'w') as f:
                for dat_path in dat_list:
                    logger.info(dat_path)
                    f.write(dat_path + '\n')

            find_event_pipeline(dat_list_path, 
                            h5_list_path,
                            #SNR_cut=2,
                            check_zero_drift = True,
                            filter_threshold = 3, 
                            on_off_first = ooo,
                            number_in_cadence = len(dat_list),
                            csv_name=csvf_path, 
                            saving=True
                            )
            
            if not os.path.exists(csvf_path):
                logger.info('No event CSV found. Continuing ...')
                continue

            # trimming regions of insensitivity
            event_df = pd.read_csv(csvf_path)
            if receiver == 'Rcvr1_2':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 1100) & (event_df['Freq'].values < 1200) |
                            (event_df['Freq'].values > 1340) & (event_df['Freq'].values < 1900))[0]
                    ]
            elif receiver == 'Rcvr2_3':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 1800) & (event_df['Freq'].values < 2300) |
                            (event_df['Freq'].values > 2360) & (event_df['Freq'].values < 2700))[0]
                    ]
            elif receiver == 'Rcvr4_6':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 4000) & (event_df['Freq'].values < 7800))[0]
                    ]
            elif receiver == 'Rcvr8_10':
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 7800) & (event_df['Freq'].values < 11200))[0]
                    ]
            elif receiver == 'Rcvr8_10_NEW':
                # sensitivity range for new X-band receiver is, like for the old receiver,
                # determined by the range where Tsys < 50 K
                trimmed_event_df = event_df.iloc[
                    np.where((event_df['Freq'].values > 7550) & (event_df['Freq'].values < 11700))[0]
                    ]
            
            trimmed_event_df.dropna(subset=['in_n_ons'], inplace=True)

            trimmed_event_df.to_csv(f'{data_loc}/{n*bs+i}_{cadence_id}_{target}_{receiver}_{node}_f3_trimmed.csv')
            tcsvf_path = f'{data_loc}/{cadence_id}_{target}_{receiver}_{node}_f3_trimmed.csv'
            
            # if len(trimmed_event_df) > 0:
            #     plot_event_pipeline(tcsvf_path, # full path of the CSV file built by find_event_pipeline()
            #             h5_list_path, # full path of text file containing the list of .h5 files
            #             filter_spec='f{}'.format(3), # filter threshold
            #             user_validation=False, # Non-interactive
            #             plot_dir=data_loc+'/pngs/')

In [ ]:
'''h5lst_list = []

for i in range(len(full_h5_list_1)):

    #print(f'Testing #{i+1} of {len(full_h5_list)//6} files ...')

    # for each set of 6 files, run FindEvent and PlotEvent

    h5_list = np.array([
            full_h5_list_1[i],
            full_h5_list_2[i],
            full_h5_list_3[i],
            full_h5_list_4[i],
            full_h5_list_5[i],
            full_h5_list_6[i],
            ])
    dat_list = np.array([
            full_dat_list_1[i],
            full_dat_list_2[i],
            full_dat_list_3[i],
            full_dat_list_4[i],
            full_dat_list_5[i],
            full_dat_list_6[i],
            ])

    # check that all h5 files in cadence exist and were searched
    # (not true for 3 files, 5 occurrences)
    if 'None' in dat_list:
        continue

    target = full_target_list[i]
    cadence_id = full_cadence_id_list[i]
    receiver = full_receiver_list[i]
    s = dat_list[0].split('blc')
    if ('spliced' in dat_list[0]) & (s[1][2] == '_'):
        node = 'blc'+s[1][:2]
    else:
        node = os.path.basename(full_h5_list_1[i])[:5]

    # This block checks the cadence type:
    # Either ABACAD, BACADA, or None (if not a real cadence).
    # ABABAB is also checked, but does not occur in this dataset.
    #cadences = full_cadence_id_list[6*i:6*i+6]
    #receivers = np.unique(full_receiver_list[6*i:6*i+6])
    targets = []
    for j in range(6):
        t = h5_list[j].split('guppi_')[1][12:-21]
        if len(t) < 3:
            t = h5_list[j].split('guppi_')[1][6:-21] # account for GJ15B cadence listed with only integer MJD
        targets.append(t.upper()) # some stars not recorded in all uppercase
    odd_targets = np.unique(targets[::2])
    even_targets = np.unique(targets[1::2])
    cadence_type = 'None'
    off_check = 0
    for t in odd_targets:
        if 'OFF' in t:
            if len(even_targets) == 1:
                cadence_type = 'BACADA'
            off_check += 1
    for t in even_targets:
        if 'OFF' in t:
            if len(odd_targets) == 1:
                cadence_type = 'ABACAD'
            off_check += 1
    if (cadence_type == 'None') & (off_check == 0):
        n_odd_ons = len(np.unique(targets[::2]))
        n_even_ons = len(np.unique(targets[1::2]))
        if (n_odd_ons == 1) & (n_even_ons == 1):
            cadence_type = 'ABABAB'
        if (n_odd_ons == 1) & (n_even_ons != 1):
            cadence_type = 'ABACAD'
        if (n_odd_ons != 1) & (n_even_ons == 1):
            cadence_type = 'BACADA'

    #if not cadence_id == 4051:
    #    continue
    if cadence_type == 'ABACAD':
        target = targets[0]
    elif cadence_type == 'BACADA':
        target = targets[1]

    #print(f'{cadence_id} {cadence_type} {target} {receiver} {targets}')

    if cadence_type == 'None':
        continue

    #print(node)
    #print(dat_list[0])

    # if (target == 'GJ412B') & (node == 'blc04') & (receiver == 'Rcvr1_2'):
    #     start_counter += 1
    
    # if start_counter == 0:
    #     continue

    h5_list_path = os.path.join(data_loc, f'{cadence_id}_{target}_{receiver}_{node}_h5_files.lst')
    h5lst_list.append(h5_list_path)
    if h5_list_path == '/datax/scratch/benjb/bl_nearby_stars/seticore_output/findevent/5152_HIP42438_Rcvr1_2_splic_h5_files.lst':
        for j in h5_list:
            print(i, j)
'''

In [ ]:
#u, c = np.unique(h5lst_list, return_counts=True)
#print(len(h5lst_list))
#print(len(u))

In [ ]:
#for i in u[np.where(c > 1)[0]]:
#    print(i)

In [8]:
len(df)

39177

In [ ]:
if __name__ == "__main__":
    # Define n+1 sets of files
    # The 1 accounts for the remainder after dividing N/n
    n = 31
    batch_size = len(df)//n
    n = 0
    batch_size = 0
    file_sets = [[str(i), df[i*batch_size:(i+1)*batch_size]] for i in range(n)]
    file_sets.append([str(n), df[n*batch_size:]])

    # Create a pool of n+1 processes
    with multiprocessing.Pool(processes=n+1) as pool:
        # Map the process_files function to each file set
        pool.map(process_files, file_sets)

    print("All files processed.")